### ISSUE TITLE
Http 500 when navigate to cart page

### ISSUE THREAD

**Issue by ArturBumbu** [woocommerce/woocommerce-google-analytics-integration#100]
![cart error](https://user-images.githubusercontent.com/18583482/28105787-f200e0ae-66d8-11e7-96f2-a4a9db1e376e.png)

#### What I expected
To see cart entries

When I add to basket any shopping items I expect when I got to cart to see the added items
#### What happened instead
the cart area is broken

To see cart entries
#### Steps to reproduce the issue
1. Go to website that has woocommerce shop
2. Add an item to the cart
3. Go to the cart

Result:
Getting http 500, cart page displayed incompletely. 
In debug log I can see follwoing error:

[12-Jul-2017 06:42:30 UTC] PHP Fatal error:  Uncaught Error: Call to undefined method WC_Cart::get_cart_item() in wp-content/plugins/woocommerce-google-analytic
s-integration/includes/class-wc-google-analytics.php:413
Stack trace:
#0 wp-includes/plugin.php(213): WC_Google_Analytics->remove_from_cart_attributes('<a href="https:...', 'ac1dd209cbcc5e5...')
#1wp-content/themes/my_theme/woocommerce/cart/cart.php(48): apply_filters('woocommerce_car...', '<a href="https:...', 'ac1dd209cbcc5e5...')
#2 wp-content/plugins/woocommerce/includes/wc-core-functions.php(105): include('/...')
#3 /wp-content/plugins/woocommerce/includes/shortcodes/class-wc-shortcode-cart.php(78): wc_get_template('cart/cart.php')
#4 /wp-content/plugins/woocommerce/includes/class-wc-shortcodes.php(70): WC_Shortcode_Cart::output('')
#5 wp-content/plugins/woocommerce/includes/class-wc-shortcodes.php(84): WC_Shortcodes::shortcode_wrapper( in wp-content/plugins/woocommerce
-google-analytics-integration/includes/class-wc-google-analytics.php on line 413

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by jcdarocha** [comment]
Hi there! 
I've got the same problem, apparently, this is from the woocommerce-google-analytic
s-integration plugin.
When i disable it, it works great.

Did you find any solution ? 

Thank you,
Jean-Charles

**Comment by ArturBumbu** [comment]
Hi Jean,

Unfortunately not.

Good luck!

Artur

**Comment by roykho** [comment]
Closed via master
