### ISSUE TITLE
Missing "ga('send', 'pageview');"

### ISSUE THREAD

**Issue by BusinessBloomer** [woocommerce/woocommerce-google-analytics-integration#101]
Hi there, just wondering why:

`ga('send', 'pageview');`

does not get output together with the others

`ga('require',...)`

Is this going to cause a problem? Is it a bug?

This is the current script as output from the plugin:

```
<script type='text/javascript'>(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)})(window,document,'script','//www.google-analytics.com/analytics.js','ga');
ga( 'create', 'UA-XXXYYYZZZ', 'auto' );
ga( 'require', 'displayfeatures' );
ga( 'require', 'linkid' );
ga( 'set', 'dimension1', 'no' );
ga( 'require', 'ec' );
</script>
```

Rodolfo

p.s. Also posted at https://wordpress.org/support/topic/gasend-pageview/

**Comment by laurendavissmith** [comment]
@BusinessBloomer The `ga('send', 'pageview');` is output in the footer not the header where GA is initialized since a pageview shouldn't be recorded until the user has had the page load
