### ISSUE TITLE
How to connect to Google AdWords?

### ISSUE THREAD

**Issue by chrisgagne** [woocommerce/woocommerce-google-analytics-integration#103]
Hello,

Thanks for making this excellent plugin! I really appreciate it.

Is anyone using this for Google AdWords? I would like to pass commerce conversions to Google AdWords so that AdWords starts to do conversion tracking. Do you have any good practices for this?

Thanks! <3

**Comment by emanweb** [comment]
You may want try this plugin: https://wordpress.org/plugins/woocommerce-google-adwords-conversion-tracking-tag/

**Comment by bor0** [comment]
Please read the following documentation. There is no need to put anything additional in the code.

https://support.google.com/adwords/answer/1704341
https://support.google.com/adwords/answer/7519537
https://support.google.com/analytics/answer/1033961
https://support.google.com/adwords/answer/2617364
