### ISSUE TITLE
Checkout Fatal Error: Cash on Delivery/Guest Checkout

### ISSUE THREAD

**Issue by teclanDesign** [woocommerce/woocommerce-google-analytics-integration#105]
We're finding a situation where the checkout process hangs when completing an order (blank white screen, no order completion). A side effect of this results in order details being empty (no product total or qty, only the order total).

It only seems to happen when:

Customer checks out as a guest (no account, not logged in)
AND
Customer chooses Cash on Delivery as the payment method

Other payment gateways and account customers can complete successfully.

It causes a fatal error in the server log, the 500 error is presumably the reason for the white screen:

mod_fcgid: stderr: PHP Fatal error: Call to a member function get_sku() on boolean in
 /var/www/vhosts/*SITE*/httpdocs/wp-content/plugins/woocommerce-google-analytics-integration/includes/class-wc-google-analytics-js.php on line 418, referer: https://www.*SITE*/checkout/

Unticking the Enhanced Ecommerce options (where the get_sku() calls seem to reside) in the plugin settings under WooCommerce > Settings moves the error reference line num to 400 but the issue still occurs. 

Deactivating the plugin completely removes the 500 error from the log and allows the order to "complete". Although we are now seeing the Order Received page, these orders are still blank which looks like this plugin may not be the root cause of the blank order issue that we are seeing and I will investigate that elsewhere but wanted to let you know about the error which is definitely caused by the plugin.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by skaiblinger** [comment]
Got the same error. 

Seems like `$order->get_product_from_item() ` was deprecated a while ago and got removed.
