### ISSUE TITLE
Difference between Adwords and Analytics

### ISSUE THREAD

**Issue by oflasmeric** [woocommerce/woocommerce-google-analytics-integration#106]
Hi ALL, 

Hope someone can help.
I've installed 2 different plugin on WP : Adwords tracking an Analytics tracking. 
I've a big difference with : the number of order, and the amount was totally different. 

Adwords return the great value, but cannont say the same for Analytics. I've a difference more than 40% !
The both plugin return to the same "thank you page".
Do you have an idea ? Someone can help me to understand / resolve the issue ?

Thanks !

**Comment by laurendavissmith** [comment]
@oflasmeric We don't have any knowledge of the Adwords extension you are referencing. Can you give us more information on what the issue that you're seeing?

**Comment by bor0** [comment]
From https://support.google.com/analytics/answer/1034383?hl=en:

> Clicks and Sessions are different metrics.
> AdWords filters invalid clicks from your report, while Analytics shows all data.
> You turned off auto-tagging for your URLs in your AdWords account.
> Make sure your AdWords Import & Export Settings are correct.

E.g., specifically:
> Google AdWords tracks Clicks, while Analytics tracks Sessions. If a user clicks on your ad twice within thirty minutes without closing his or her browser, this is registered by Analytics as one session, even if the user left your site and then returned shortly after. For example, if a user clicks on your ad once, clicks the back button, and then clicks your ad again, AdWords registers two clicks while Analytics registers one session.

etc.
