### ISSUE TITLE
Feature Request: Hook to Disable Tracking

### ISSUE THREAD

**Issue by dominic-p** [woocommerce/woocommerce-google-analytics-integration#108]
What do we think about adding a hook so other plugins can control whether the tracking is enabled in certain situations?

My use case is that I want to exclude my traffic from tracking. Unfortunately, I have several dynamic IPs, so I have written a plugin to periodically update my IPs. Now, I just need a way to disable tracking on traffic from those IPs.

I'm thinking we could simply wrap [this line](https://github.com/woocommerce/woocommerce-google-analytics-integration/blob/1.4.3/includes/class-wc-google-analytics.php#L349) with `apply_filters( ...`. I would be happy to put together a pull request if you would like.

**Comment by lkraav** [comment]
I think it makes more sense to block admin tracking at browser level. Private windows already block analytics by default, and there are several browser plugins to help, too. Like https://tools.google.com/dlpage/gaoptout

**Comment by dominic-p** [comment]
Thanks for the feedback. I am currently trying to transition away from those strategies because I have found them cumbersome to manage:

- Every browser in the organization must have the extension installed
- Some mobile browsers don't support these extensions
- It's hard to remember to always use private windows
- Site [security headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) can block the inline js that these browser extensions attempt to add rendering them useless

**Comment by dominic-p** [comment]
Just to follow up on this. There could be other use cases for allowing plugins to control analytics tracking injection as well. For example, I could imagine some websites may want to disable tracking altogether in certain countries/regions for regulatory compliance.
