### ISSUE TITLE
Update the assets on .org

### ISSUE THREAD

**Issue by laurendavissmith** [woocommerce/woocommerce-google-analytics-integration#110]
We need to update the assets on the .org page for this extension. Images need updating and the text needs to be looked through for any missing or additional information.

**Comment by laurendavissmith** [comment]
This would include making sure the plugin is compatible with latest version(s) of WP so we can remove the notice on the .org docs

**Comment by bor0** [comment]
Tested this extension and seems to be working fine with WP 4.9.4, latest WC master. No notices in error log.

Some tracking results:
<img width="1044" alt="screen shot 2018-03-09 at 10 24 16 am" src="https://user-images.githubusercontent.com/1620929/37200184-5470d3da-2384-11e8-8b75-19c44c9ed1f8.png">

I will be updating readme.txt to reflect compatibility.

**Comment by roykho** [comment]
@bor0 should we close this after the assets have been updated?

**Comment by bor0** [comment]
@roykho what assets? I thought it is only about confirming compatibility with latest WP?

**Comment by bor0** [comment]
Ok in that case we should also wait for gtag implementation as it will change Settings screen.
