### ISSUE TITLE
use Global Site Tag tracking to be compatible with free "Google Analytics Dashboard for WordPress"

### ISSUE THREAD

**Issue by Tobias-Conrad** [woocommerce/woocommerce-google-analytics-integration#112]
Changelog is here:
https://deconf.com/adding-gtag-js-to-your-site/
From the changelog: If you’re using an Ecommerce tracking plugin, make sure the plugin supports the new Global Site Tag tracking code.

So i expect that you in free and paid version of woocommerce-google-analytics-integration
use Global Site Tag tracking to be compatible with free "Google Analytics Dashboard for WordPress".

Thank you

**Comment by laurendavissmith** [comment]
@Tobias-Conrad What are you looking for from gtag that isn't provided already from the analyticsjs implementation?

**Comment by bor0** [comment]
As far as I understand this is a compatibility request with [Google Analytics Dashboard for WP](https://deconf.com/google-analytics-dashboard-wordpress/).

But I don't understand what needs to be done in order for them to be compatible? What issues are you running into?

**Comment by bor0** [comment]
I am working on implementing support for gtag.js in #102.
