### ISSUE TITLE
Include mention of GA Pro 

### ISSUE THREAD

**Issue by avivapinchas** [woocommerce/woocommerce-google-analytics-integration#115]
Users of our free GA integration might be looking for additional features they could find in the[ GA Pro version](https://href.li/?https://woocommerce.com/products/woocommerce-google-analytics-pro/). We should make it easy/obvious how to get that extension.

**Comment by avivapinchas** [comment]
Design thoughts: 
`Display a wp notice to inform folks about the upgrade path once they’ve reached X completed orders. X probably being something between 10 – 100.

**Comment by bor0** [comment]
@avivapinchas do you have some text that we can use for this?
E.g.
```
Title: Introducing Google Analytics Pro
Description: Visit Google Analytics Pro <a href="https://woocommerce.com/products/woocommerce-google-analytics-pro/" target="_blank">here</a> for better analytics tracking!'
```

**Comment by avivapinchas** [comment]
Sure thing - suggested copy: 
>*Get detailed insights into your sales  with Google Analytics Pro*
> Add advanced tracking for your sales funnel, coupon usage and more. 
>[Learn more >]

`Learn more` should be a button that goes to: `https://woocommerce.com/products/woocommerce-google-analytics-pro/?utm_source=product&utm_medium=upsell&utm_campaign=google%20analytics%20free%20to%20pro%20extension%20upsell`

Note that I added UTM parameters there so we can track this traffic.
