### ISSUE TITLE
Ecommerce data not tracked within GA

### ISSUE THREAD

**Issue by johndcoy** [woocommerce/woocommerce-google-analytics-integration#118]
#### What I expected

To see transaction data in Google Analytics dashboard under **Conversions > Ecommerce > Overview**. Currently only enhanced ecommerce data is shown.

#### What happened instead

Transaction and Ecommerce specific data is not being tracked.

#### Steps to reproduce the issue

1. Install and activate plugin
2. Add Google Analytics ID
3. Wait for propagation. :)
4. Go the Google Analytics dashboard then **Real-time > Overview** to see real-time checkout process. 
![Screenshot](http://cld.wthms.co/PorqPj+)
Image Link: http://cld.wthms.co/PorqPj
5. Then review **Conversions > Ecommerce > Overview** within Google Analytics dashboard to see no data. The only way to get data to show is to view the Enhanced Ecommerce product link.
![Screenshot](http://cld.wthms.co/d52bHh+)
Image Link: http://cld.wthms.co/d52bHh

Enhanced Ecommerce view:
![Screenshot](http://cld.wthms.co/9T8tfF+)
Image Link: http://cld.wthms.co/9T8tfF

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by johndcoy** [comment]
Required Ecommerce view to be enabled in Google Analytics: https://docs.woocommerce.com/document/google-analytics-integration/#section-2

**Comment by johndcoy** [comment]
@bor0 Looks like this is an issue. Can you please test PayPal and Stripe as well and view the "Today" view within Ecommerce > Overview

Thanks!

**Comment by madeincosmos** [comment]
@woocommerce/extendables can someone look into this? I'm unable to see any e-commerce stats at all on my Google Analytics account. Here is the Real-time tab:

![Screenshot](http://cld.wthms.co/C9nbHJ+)
Screenshot: http://cld.wthms.co/C9nbHJ

And here is **Conversions > E-commerce**:

![Screenshot](http://cld.wthms.co/RlyzVr+)
Screenshot: http://cld.wthms.co/RlyzVr

**Comment by johndcoy** [comment]
@madeincosmos  I tested this with Amazon Pay using incognito (not logged into the WP Admin ) and I was not able to replicate any problems. You’ll see here GA recognized that I added a product to the cart, including the product price.

http://cld.wthms.co/tFKIWM

Viewing the Ecommerce Overview data showed the same information.

http://cld.wthms.co/1rDL35

So I guess the Ecommerce data in Google Analytics isn’t in real time as it could take 5 or so minutes before the data to show, and purchases have to be made while not logged in as admin. **All of that sounds silly but could you test as a guest and as a logged in customer to confirm?**

**Comment by budzanowski** [comment]
I have tester it. Everything works. I see all the data as long as I make actions as non wp-admin user. Then waiting a bit is required for the GA panel to be up to date. Looks like we can close this?

**Comment by budzanowski** [comment]
@pedroapfilho could you check your site using https://chrome.google.com/webstore/detail/tag-assistant-by-google/kejbdjndbnbjgmefkgdddjlbokphdefk as a logged out user. Make some transactions and record ( using chrome plugin ) what GA plugin is dong.

**Comment by budzanowski** [comment]
It works for me 
![image](https://user-images.githubusercontent.com/17271089/42894102-52e2c52a-8ab6-11e8-9242-732e977d311e.png) both as logged out and as a logged in customer. The chrome plugin is the fastest way of checking.

**Comment by pedroapfilho** [comment]
Seems that this only occur when the payment method makes the user leaves the page, like PayPal...

When the user pays with some transparent checkout payment method, it appears on the Analytics.

**Comment by budzanowski** [comment]
The requirement for the payment to work is outlined in the documentation in the following way:
>Purchase Transactions: Track purchases on your site, including data like revenue, tax, refunds, shipping and more. This requires a payment gateway that redirects to the thank you/order received page after payment. Some popular options that do this are Stripe, PayPal powered by Braintree, PayPal Express Checkout and Square.

@pedroapfilho Is your Paypla plugin redirecting back to the `thank you/order received` page?

**Comment by pedroapfilho** [comment]
@budzanowski, idk if it's obligatory to return to the page, I think that the user can just go away after he pays at PayPal (I'm using PayPal Standard)

I got it, it was working into a few days ago, but now seems that all customers are going away after they pay the order (maybe something at the PayPal page).

You can close this issue (for me, at least)

**Comment by laurendavissmith** [comment]
Closing since it sounds like this is resolved now but we can reopen if anything comes up
