### ISSUE TITLE
Why removing product line from cart page does not generate a GA Event?

### ISSUE THREAD

**Issue by rouffj** [woocommerce/woocommerce-google-analytics-integration#119]
Hi everyone, thanks for your hard work for the integration of Google Analytics on WooCommerce. 

I'm using WooCommerce 3.3.4, Wordpress 4.9 and PHP7.0.
 
#### What I expected

When I go to the "/cart/" page then update the number of articles or remove a product line I would expect that action sends to Google Analytics an event like "add to cart" or "remove from cart".
   

#### What happened instead

Instead of that expected behaviour, there is no call to Google Analytics when there is an update of the cart from the "/cart" page. 

Is it a normal behaviour? Do I need to activate something on the backend? 

Thanks you for your help.

Joseph.

**Comment by laurendavissmith** [comment]
@rouffj Do you have Enhanced Ecommerce enabled in the settings?

**Comment by rouffj** [comment]
@laurendavissmith Yes Enhanced Ecommerce is enabled.

Working scenarios:
- When i add a product via the product listing (button 'Add to cart'), GA event is sent.
- When i remove a product via the cart overview on the header, GA event is sent.

Not working scenarios:
- When i remove a product from the cart page "/cart", GA event is NOT sent :(.
- When i update quantity of a product from the cart page "/cart", GA event is NOT sent :(.

Here is a screenshot of the settings:
![reglage-google-analytics](https://user-images.githubusercontent.com/24047/40007599-8302e2ea-579d-11e8-94cd-2e260dc8b61d.png)

**Comment by laurendavissmith** [comment]
@rouffj thanks for the detailed report, i've marked it as a bug so we can take a look

**Comment by rouffj** [comment]
@laurendavissmith Here is the steps to reproduce the failing scenario "When i remove a product from the cart page /cart, GA event is NOT sent":
1. Go to product listing
1. From product listing, add a product to cart via "Add to Cart" button
1. Go to cart page
1. (important step) Update quantity of a product from cart page and click "Update cart" button
1. (important step) without reloading the page, click on red cross to remove a product.

On step 5, there will be no GA event sent. I think this bug is due to ajax reload of the cart, because when at the end of step 4 i reload the page, the GA event is sent.

So it is a bug a little tricky to reproduce :).
