### ISSUE TITLE
Problem when jQuery is not yet loaded on page

### ISSUE THREAD

**Issue by AndreiIgna** [woocommerce/woocommerce-google-analytics-integration#121]
We use the plugin on a few websites and noticed a issue on the ones with more aggressive cache rules. When JS is loaded deferred, the plugin produces this error

<img width="358" alt="screen shot 2018-06-04 at 12 02 01" src="https://user-images.githubusercontent.com/263021/40911707-d9f46d1e-67ef-11e8-8b87-d332494fc896.png">

Most of the functionality still works, there are a few actions which are not tracked and produce that error. For example this one https://github.com/woocommerce/woocommerce-google-analytics-integration/blob/master/includes/class-wc-google-analytics-js.php#L160

Because the tracking codes are so simple and use just minimal helpers from jQuery, it would be better to use plain JS for these. `querySelector` is available in all used browsers https://caniuse.com/#search=querySelector and would improve the cross-plugin compatibility

Cheers

**Comment by Danw33** [comment]
**+1**

We're also having this issue as our JS is deferred too.

With other plugins, we have overcome this by using `add_filter` with `str_replace` to filter each inline-script output that requires jQuery, and wrapping the script with a `DOMContentLoaded` event listener before returning it, a little bit like this:

```javascript
window.addEventListener('DOMContentLoaded', function() { 
    // ...
});
```

This _could_ work for the WooCommerce GA plugin too, if the script outputs were filterable which currently they are not.

I agree with @AndreiIgna that most of these scripts have a simple vanilla JS alternative which would be much better, and in addition to this it would be great if the plugin did a bit of `apply_filters` magic on the scripts before they are echo'ed so that devs can manipulate them as they desire.

**Comment by leemason** [comment]
+1

@laurendavissmith / @mattyza / @bro0 is this on anyone's radar, it's been two months since the issue was opened?

If not, might a PR be accepted changing the scripts to be vanilla JS that are filterable?

**Comment by jmock** [comment]
Having the same issue. I just filed a ticket with Woo about it before I found this, but since this has been sitting here with no response since June, I guess I'm not really expecting much :/

**Comment by bor0** [comment]
@leemaon feel free to open a PR, I'll be happy to review it. AFAIK, this is low on our (big) priority list.

**Comment by bor0** [comment]
@leemason feel free to open a PR, I'll be happy to review it. AFAIK, this is low on our (big) priority list.

**Comment by Buzut** [comment]
Seems like the plugin works without JS if you deactivate universal analytics.

**Comment by laurentdebricon** [comment]
Someone has a fix ?
This line 
`		add_action( 'wp_footer', array( $this, 'loop_add_to_cart' ) );
` 
should be wrapped in a 
```
window.addEventListener('DOMContentLoaded', function() { 
    // ...
});
```

but i don't know how to do that yet :P :(

**Comment by laurentdebricon** [comment]
> I agree with @AndreiIgna that most of these scripts have a simple vanilla JS alternative which would be much better, and in addition to this it would be great if the plugin did a bit of `apply_filters` magic on the scripts before they are echo'ed so that devs can manipulate them as they desire.

@Danw33 
i can see a hook now in wc-core-function.php , which is used by woocommerce-google-analytics
		echo apply_filters( 'woocommerce_queued_js', $js ); // WPCS: XSS ok.

Would you mind sharing your code ?

**Comment by laurentdebricon** [comment]
Hello,
i have written the code you put in in your theme function.php , and issue is solved.
```

function filter_for_woocommerce_wp_rocket( $js ){
	$head = explode( '<script type="text/javascript">', $js );
	$tail = explode( '</script>', $head[1]);

	$edited = $head[0] .'<script type="text/javascript">document.addEventListener("DOMContentLoaded", function(event) {'.$tail[0].'})</script>'. $tail[1];

	return $edited;
}

add_filter( 'woocommerce_queued_js', 'filter_for_woocommerce_wp_rocket' );
```

**Comment by ugurgok** [comment]
> Hello, i have written the code you put in in your theme function.php , and issue is solved.
> 
> ```
> 
> function filter_for_woocommerce_wp_rocket( $js ){
> 	$head = explode( '<script type="text/javascript">', $js );
> 	$tail = explode( '</script>', $head[1]);
> 
> 	$edited = $head[0] .'<script type="text/javascript">document.addEventListener("DOMContentLoaded", function(event) {'.$tail[0].'})</script>'. $tail[1];
> 
> 	return $edited;
> }
> 
> add_filter( 'woocommerce_queued_js', 'filter_for_woocommerce_wp_rocket' );
> ```

It doesn't work for me cause there is still jQuery tag. I modified your code maybe it will work for simple use

```
function filter_for_woocommerce_wp_rocket( $js ){
	$head = explode( '<script type="text/javascript">
jQuery(function($) { ', $js );
	$tail = explode( ');\n</script>\n', $head[1]);

	$edited = $head[0] .'<script type="text/javascript">document.addEventListener("DOMContentLoaded", function(event) {'.$tail[0].'})</script>'. $tail[1];

	return $edited;
}

add_filter( 'woocommerce_queued_js', 'filter_for_woocommerce_wp_rocket' );
```

but there are still many jQuery element usages. 
like


		```
	$( '.products .post-2474 a' ).on( 'click', function() {
				if ( true === $(this).hasClass( 'add_to_cart_button' ) ) {
					return;
				}

				ga( 'ec:addProduct', {
					'id': '2474',
					'name': 'Product name',
					'category': 'Product Cat',
					'position': '2'
				});

				ga( 'ec:setAction', 'click', { list: 'Product List' });
				ga( 'send', 'event', 'UX', 'click', ' Product List' );
			});
```

**Comment by martynmjones** [comment]
As part of the upcoming version `2.0.0` release, we have removed jQuery as a dependency so closing this issue.
