### ISSUE TITLE
Can't enable Enhanced eCommerce

### ISSUE THREAD

**Issue by srakl** [woocommerce/woocommerce-google-analytics-integration#122]
Hi, i've got everything setup for this plugin, but can't seem to enable the "Enable Enhanced eCommerce"

Everytime i check it and save, when the page refreshes it's unchecked again.
I already followed the steps here https://support.google.com/analytics/answer/1009612?hl=en under "Enable Ecommerce for a view" too.

The other plugin i have installed is the "Google Analytics Dashboard for WP (GADWP)" and under the Ecommerce Tracking: i enabled  the "enhanced ecommerce plugin" option too

Any idea what i'm doing wrong? Thanks
![untitled2](https://user-images.githubusercontent.com/3472875/40946370-b49b40ba-688f-11e8-9bb6-761fd060769d.png)
![untitled3](https://user-images.githubusercontent.com/3472875/40946372-b4d048aa-688f-11e8-90c6-1c17572ae53d.png)
![untitled](https://user-images.githubusercontent.com/3472875/40946373-b5029878-688f-11e8-970e-f370a9d256e2.png)

**Comment by laurendavissmith** [comment]
I'm not seeing that issue on my end, what version of WooCommerce and WordPress are you running?

**Comment by srakl** [comment]
Sorry forgot to include that info. Here it is 
![untitled](https://user-images.githubusercontent.com/3472875/40996094-90dd0eca-6933-11e8-8197-f4bd69fc0c25.png)
![untitled2](https://user-images.githubusercontent.com/3472875/40996102-9484a54c-6933-11e8-9c5a-642d20127768.png)
![untitled3](https://user-images.githubusercontent.com/3472875/40996114-9880b672-6933-11e8-8f18-acc0799b0aa5.png)

**Comment by johndcoy** [comment]
@laurendavissmith I was not able to replicate this. The plugin is working. You'll see here GA recognized that I added a product to the cart, including the product price.

![Screenshot](http://cld.wthms.co/tFKIWM+)
Image Link: http://cld.wthms.co/tFKIWM

Viewing the Ecommerce Overview data showed the same information.

![Screenshot](http://cld.wthms.co/1rDL35+)
Image Link: http://cld.wthms.co/1rDL35

@srakl The issue you're having may be related to the payment gateway. For transaction tracking to work properly, you will need to use a payment gateway that redirects the customer back to a WooCommerce order received/thank you page.

Closing this issue. Please post any help you need on the [WooCommerce Google Analytics forums](https://wordpress.org/support/plugin/woocommerce-google-analytics-integration/) and we can help you there.
