### ISSUE TITLE
Backend down

### ISSUE THREAD

**Issue by kevin25** [woocommerce/woocommerce-google-analytics-integration#126]
After pull the latest version from github, my backend was down.

> 2018/06/30 02:44:52 [error] 15688#0: *10213 FastCGI sent in stderr: "PHP message: PHP Parse error:  syntax error, unexpected 'text' (T_STRING), expecting ';' in /home/domain/public/wp-content/plugins/woocommerce-google-analytics-integration/includes/class-wc-google-analytics.php on line 340" while reading response header from upstream, client: xxx.xxx.xxx.xxx, server: www.domain.com, request: "GET / HTTP/2.0", upstream: "fastcgi://unix:/var/run/php7.sock:", host: "www.domain.com", referrer: "https://www.domain.com/wp-admin/plugins.php"

**Comment by roykho** [comment]
Please try master now.
