### ISSUE TITLE
Fatal error: Call to undefined function session_status() 

### ISSUE THREAD

**Issue by Pasteo2018** [woocommerce/woocommerce-google-analytics-integration#127]
Hi,
from this afternoon my site is down ... he gives me the following error:

Fatal error: Call to undefined function session_status() in /web/htdocs/www.giansport.it/home/wp-content/plugins/enhanced-e-commerce-for-woocommerce-store/includes/class-wc-enhanced-ecommerce-google-analytics-integration.php on line 35 

my PHP version: 5.3.29

Thanks for help

**Comment by roykho** [comment]
I believe you're posting this in the wrong repo. You're probably looking for these folks here https://wordpress.org/plugins/enhanced-e-commerce-for-woocommerce-store/

**Comment by Pasteo2018** [comment]
ok ... I'm sorry
