### ISSUE TITLE
E-Commerce Transaction Tracking Broken After Update to v1.4.10 

### ISSUE THREAD

**Issue by harishankerr** [woocommerce/woocommerce-google-analytics-integration#145]
#### What I expected

All E-Commerce transactions are being tracked by Google Analytics, after updating to 1.4.10.

#### What happened instead

E-Commerce transaction tracking does not work after updating to 1.4.10. There have been several reports of this problem in the forums as well:

* https://wordpress.org/support/topic/ecommerce-tracking-stopepd-on-1-4-10/
* https://wordpress.org/support/topic/e-commerce-transaction-is-not-tracking-in-google-analytics/

#### Steps to reproduce the issue

1. Set up Google Analytics 1.4.10 along with WordPress 5.2.2 and WooCommerce 3.6.5. Connect to Google Analytics. Make sure transaction tracking is enabled, as mentioned in the docs: https://docs.woocommerce.com/document/google-analytics-integration/#tracking-options
2. Try making a test transaction using a payment gateway (like Stripe).
3. Go to Google Analytics, and check if the transaction has been recorded.
4. You will see that the transaction has not been recorded and does not show up in Analytics.
5. Try downgrading the extension to 1.4.9 and try placing another transaction.
6. Go to the Google Analytics dashboard. You will see that the transaction has been recorded there. 

#### Additional notes

Marking this as `Critical` since the update breaks core plugin functionality. 

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by bor0** [comment]
The only change introduced in 1.4.10 seems to be #144. In other words if they check the option `Enable Standard Tracking` it should work fine. Alternatively we could set the default to `'yes'`?

**Comment by roykho** [comment]
@bor0 yes that is correct and could be the alternative.
