### ISSUE TITLE
Analytics column is not responsive in wp-admin

### ISSUE THREAD

**Issue by treibalen** [woocommerce/woocommerce-google-analytics-integration#146]
Reported in 14265990-hc

#### What I expected

A responsive Analytics column.

#### What happened instead

![https://cld.wthms.co/5Bhf61](https://cld.wthms.co/5Bhf61+) 
Full Size: https://cld.wthms.co/5Bhf61

I didn't have a Google Analytics ID to add on my test site, but the screenshot user shared is from a site with only WooCommerce and GA enabled.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by mikejolley** [comment]
This is WP SEO. This extension does not add columns within admin.
