### ISSUE TITLE
Can't Update to Last Version

### ISSUE THREAD

**Issue by pvnanini** [woocommerce/woocommerce-google-analytics-integration#148]
#### What I expected
Update the plugin without issues.

#### What happened instead
Error

#### Steps to reproduce the issue
Update the plugin via admin or ftp gives error

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by hanneskiivet** [comment]
I had the same issue. All other plugins were updating normally, but not this one. Temporary solution:

1. in admin select the plugin to update and click update.
2. on the next page (without result) using view source or inspect element (developer tools) copy the URL of the updating iframe (eg https://EXAMPLE/wp-admin/update.php?action=update-selected&plugins=woocommerce-google-analytics-integration%2Fwoocommerce-google-analytics-integration.php&_wpnonce=RANDOM)
3. go to the URL (eg new tab).

**Comment by E-VANCE** [comment]
Same issue here, updating the plugin on the plugins page works though...
