### ISSUE TITLE
FATAL ERROR on checkout Thank You page

### ISSUE THREAD

**Issue by bakoline** [woocommerce/woocommerce-google-analytics-integration#152]
Hi,

This is very strange…

Checkout thank you page works fine (when logged in) but eCommerce transactions/orders are not tracked by google analytics.

From INCOGNITO tab checkout THANK YOU page has this error and there are below errors in error_log

screenshot: https://i.imgur.com/P7otLDC.png

`[20-Sep-2019 14:17:26 UTC] PHP Fatal error:  Uncaught Error: Call to a member function get_sku() on boolean in /home/transfer/public_html/domains/transfersgeorgia.com/wp-content/plugins/woocommerce-google-analytics-integration/includes/class-wc-google-analytics-js.php:400
Stack trace:
#0 /home/transfer/public_html/domains/transfersgeorgia.com/wp-content/plugins/woocommerce-google-analytics-integration/includes/class-wc-google-analytics-js.php(337): WC_Google_Analytics_JS->add_item_universal(Object(Automattic\WooCommerce\Admin\Overrides\Order), Object(WC_Order_Item_Product))
#1 /home/transfer/public_html/domains/transfersgeorgia.com/wp-content/plugins/woocommerce-google-analytics-integration/includes/class-wc-google-analytics-js.php(284): WC_Google_Analytics_JS->add_transaction_universal(Object(Automattic\WooCommerce\Admin\Overrides\Order))
#2 /home/transfer/public_html/domains/transfersgeorgia.com/wp-content/plugins/woocommerce-google-analytics-integration/includes/class-wc-google-analytics.php(332): WC_Google_Analytics_JS->add_transaction(Object(Automa in /home/transfer/public_html/domains/transfersgeorgia.com/wp-content/plugins/woocommerce-google-analytics-integration/includes/class-wc-google-analytics-js.php on line 400`

**Comment by mikkamp** [comment]
Also posted in: https://wordpress.org/support/topic/fatal-error-on-checkout-thank-you-page/

Seems it was a plugin, which in this case is causing an issue when loading the product from the line item. Would be nice to do some additional checks so it doesn't create a fatal error. But without a valid product being returned we can't populate all the tracking data.
