### ISSUE TITLE
Only enable after user consent

### ISSUE THREAD

**Issue by zwiesman31** [woocommerce/woocommerce-google-analytics-integration#153]
#### What I expected

The latest ruling of the European court of justice declared that all, non-functional cookies (as ga-tracking) need to be disabled by default and only enabled after the user gives consent.

Several cookie-banner plugins allow checking the consent state by a function or allow to enable/disable code in their options.

We should add an option that checks if there is user consent before the GA cookies are enabled.

#### What happened instead

GA cookies are enabled by default, regardless of user's consent.

Reported in WP.org forum here: https://wordpress.org/support/topic/feature-request-only-enable-after-user-consent/

Labeling as a `Bug` for now, but `Enhancement` may be better.
-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by laurendavissmith** [comment]
@zwiesman31 switching to enhancement and removing critical

**Comment by florianbepunkt** [comment]
An immediate improvement in my oppinion would be to check, if the JavaScript was loaded before executing analytics functions.

There are several plugins that allow consent management and block JavaScripts. For example we use Borlabs Cookie (not affiliated with them): https://borlabs.io/borlabs-cookie/

This allows us to block Google Analytics unless the user consented to it. However, if we block the JS, we get several errors like

`Uncaught ReferenceError: ga is not defined`

Would it be possible to add a simple check in the methods whether the tracker is defined? I could put together a PR if needed.

**Comment by dougaitken** [comment]
A request for this from here - https://wordpress.org/support/topic/google-analytics-code-gets-inserted-automatically-on-woocommerce-parts/

**Comment by danbachar** [comment]
any news on this? I imagine a lot of people are having problems getting their cookie notice plugins to play nicely with this (me included)

**Comment by Babylon1999** [comment]
Reported here as well: https://wordpress.org/support/topic/borlabs-cookie-gtag-question/

**Comment by webdados** [comment]
Any news on this? We're in 2023 and the official WooCommerce Google Analytics Integration still doesn't comply with GDPR.

I've been able to use your `woocommerce_gtag_snippet` filter to alter the tag to enable consent mode and tcf support, then take out the `config` part for later firing after the consent is granted by the site visitor. It "works" but it's very ugly!
Also, any script that you inject directly on the page footer, like the `purchase` event, for example, are not filterable and so there's no way to pick them up for later processing, making them run before the actual config (that waited for the reply from the consent platform), which cause the event NOT to be recorded on GA at all.

In short, it's not possible to use only the `woocommerce_gtag_snippet` filter to enable consent mode, as you mention here: https://wordpress.org/support/topic/consent-mode/
Even if it was possible, it's quite ugly and prone to be rendered useless if you change anything on the plugin.

Users can not trust the official WooCommerce Google Analytics Integration and no, `javascript:gaOptout()` is not an option, as CAN use GA4 (IP anonymous by default) in consent mode (cookieless if the user chooses to) using a consent platform and comply with the law.

The plugin should have a TCF 2.0 consent compatibility mode (activated by option) and if active, it needs to set GA to [consent mode](https://support.google.com/analytics/answer/9976101?hl=en) and TCF [compatibility mode](https://support.google.com/analytics/answer/10022331).

I'm sure you can, better than I, come up with the best approach, but it could look roughly like this: https://gist.github.com/webdados/d2c5535887485ebea723670e92c8b6d4

**Comment by tomalec** [comment]
We are going to do a major code refactoring incl. removing Universal Analytics https://github.com/woocommerce/woocommerce-google-analytics-integration/pull/322. After that, we start to add basic support for consent mode https://github.com/woocommerce/woocommerce-google-analytics-integration/pull/361
We'll improve the support iteratively. The brief plan looks like follow:
1. Add a basic consent mode snippet, that disallows all parameters for EEA region visitors
    - the default state could be customized with a code snippet
    - consent can be updated by other extensions, or custom code that provide UI for `gtag('consent', 'update', {…})`
2. Polish the lifecycle of our events, to make sure we allow customizations before any `gtag` hits
3. Add basic customization via UI in the Settings
4. Explore integrations with WP Consent API plugins

**Comment by jacekjarzab** [comment]
@tomalec when do you think you can release the patch?
As far I can tell in needs to happen before 6th of March.

**Comment by tomalec** [comment]
We released it [this Tuesday in `2.0.0`](https://github.com/woocommerce/woocommerce-google-analytics-integration/releases/tag/2.0.0)

Please refer to the [README for consent mode customizations](https://github.com/woocommerce/woocommerce-google-analytics-integration#consent-mode)
