### ISSUE TITLE
GA registering sales for failed finance

### ISSUE THREAD

**Issue by thelar** [woocommerce/woocommerce-google-analytics-integration#155]
I'm using Deko/Klarna for finance on a site I've just built and I use a third party plugin for the Deko payment gateway integration. The issue that I have is that the payment gateway works by creating an order number and redirecting the customer to the order-received page BEFORE taking them to Klarna to complete their finance application. 

The issue with this of course is that This plugin is sending the sale to GA and and it's skewing all of my conversion, revenue etc because most of time, people fail the finance application.

Strangely, the PPC tracking IS accurate, this is implemeted via some Google Tag manager script, but it must be tracking sales in a different way to this plugin??

It is difficult to reproduce because it requires access to the third party Deko finance plugin - I am happy to share this with you if you feel it's something you need though.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by budzanowski** [comment]
Hello!

This needs to be addressed by the Deko payment plugin developers. According to the documentation of the Google Analytics plugin:

> Purchase Transactions: Track purchases on your site, including data like revenue, tax, refunds, shipping, and more. This requires a payment gateway that redirects to the thank you/order received page after payment. Some popular options that do this are Stripe, Braintree for WooCommerce, PayPal Checkout, and Square.

The out-of-order flow for the Deko payment makes it impossible for Google Analytics to understand that the payment was not made. I don't think that we can do anything to help in this situation.
