### ISSUE TITLE
Receiving fatal error on Listing Impression

### ISSUE THREAD

**Issue by petersontubini** [woocommerce/woocommerce-google-analytics-integration#156]
Hi Guys,

I'm receiving a fatal error "Call to a member function get_id() on null". I've activated WP Debug and I've searched the function that is giving the error and I've found the function that is getting the error.

It seems that is not checking if the product is null before adding to JS. Can you guys help me on it?

![image](https://user-images.githubusercontent.com/7456065/72474772-4e9b2a00-37c8-11ea-9406-393044e70e82.png)

**Comment by findingsimple** [comment]
Hi @petersontubini are you still seeing this issue?

I'm going to close for now - I recommend opening a discussion on the public forums or if you are a paying WooCommerce.com Customer you can get help faster at WooCommerce.com > My Account > Tickets.

https://wordpress.org/support/topic/guide-for-using-the-woocommerce-google-analytics-integration-forum/
