### ISSUE TITLE
Issue on purchases conversion 

### ISSUE THREAD

**Issue by PaulDABIN** [woocommerce/woocommerce-google-analytics-integration#158]
#### What I expected

I decided to try this extension to report on Google Analytics purchases and revenues. 

Purchases and revenues are fully displayed on woocomerce/purchases. As you can see on the next picture, I had 2 purchases (89€ the January 25 and 498€ the January 28th) and the others were attempts canceled by customers. 

![image](https://user-images.githubusercontent.com/7039458/73659124-e1c3d300-4695-11ea-94ff-242b3ff1a2af.png)

#### What happened instead

I have 2 purchases on google analytics but as you can see GA displays failed attempts (date and revenue) and not the 2 purchases. Do you have any idea how to fix this ? I think that this issue is due to the fact that there is no automatic redirection on my thank you once the paiement is proceed on my paiement gateway.

![image](https://user-images.githubusercontent.com/7039458/73660002-9d393700-4697-11ea-8dc6-3606adbfc144.png)

**Comment by grigorijurasov** [comment]
Hi there,

Indeed, a redirect to the thank you page is necessary for Google Analytics to record a purchase.

I haven't been able to replicate this at all though - no e-commerce transactions are recorded at all so I'm opening a new bug report here:  

https://github.com/woocommerce/woocommerce-google-analytics-integration/issues/164
