### ISSUE TITLE
Manual WP 5.4 test and version bump

### ISSUE THREAD

**Issue by roykho** [woocommerce/woocommerce-google-analytics-integration#161]
For dot.org extensions, when the header `Tested up to` is out of date with the current WordPress release, customers will see a warning about this. .org extensions are much more prominent in where it shows the warning and to prevent unnecessary complains, we should bump the `Tested up to` version.

They see scary warning like this ![](https://d.pr/i/IPmMU8+)

This entails manually testing WP 5.4 and making sure all the basic features of the extension works with it without any issues/warnings/notices.

**Comment by mikkamp** [comment]
Did compatibility testing with WP 5.4 RC 1 and WC 4.0 RC 2.

Confirmed the backend settings screens and tracking on the frontend continued working.

Bumped versions and released: https://wordpress.org/plugins/woocommerce-google-analytics-integration/
