### ISSUE TITLE
Google Analytics Pro notices option will not be set if a site already has 100 completed orders on plugin activation

### ISSUE THREAD

**Issue by lukecav** [woocommerce/woocommerce-google-analytics-integration#163]
`woocommerce_google_analytics_pro_notice_shown`  option will never get set is the site where the plugin is activated on already has 100 completed orders. Then the sad query will keep being run.

**Comment by madeincosmos** [comment]
I'm seeing the same behavior on my test site - if there's more than 100 orders on first activation, the plugin will try to count all existing orders on every page load, and there's nothing we can do to stop it.

Ideally, if we detect it once that there are more than 100 orders created on the site already, we could save it as an option to avoid running the whole order count query on every run (which can be quite time-consuming on sites with lots of orders):

https://github.com/woocommerce/woocommerce-google-analytics-integration/blob/08ad9cec1924ccd34ef24f6769c1b32e551dbcaa/woocommerce-google-analytics-integration.php#L134:L139
