### ISSUE TITLE
Ecommerce Transaction & revenue not tracked in GA 

### ISSUE THREAD

**Issue by NathanaelServiceCompany** [woocommerce/woocommerce-google-analytics-integration#167]
#### What I expected

I expected to access E-commerce reports under Conversions. 
#### What happened instead
No transactions tracked

#### Steps to reproduce the issue

1 . Google analytics already installed through another plugin : GA Google Analytics (By JeffStar). Method chosen Universal Analytics. (I previously tested with Global Site Tag, but same issue faced). Also I made sure that Enhanced Ecommerce is enabled in the GA settings. 
2. Woocommerce Google analytics integration plugin installed and activated. Standard tracking not toggled on since already integrated. All Enhanced Ecommerce buttons toggled on. 
3. After several weeks still no e-commerce data tracked and I don't understand why. 

Payment method is Cash on Delivery only. I can definitely see the checkout pages being tracked in the All pages report but no E-commerce data. 

Thank you for your help ! 

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by findingsimple** [comment]
Some quick notes

[GA supports multiple tags](https://support.google.com/analytics/answer/1032400?hl=en) and I can confirm both tags are being loaded in a basic configuration

![Screen Shot 2020-11-02 at 12 54 43 pm](https://user-images.githubusercontent.com/355014/97823995-9ca6fd00-1d0a-11eb-98ad-fc1808670379.png)

Note that the WooCommerce Google Analytics integration loads after the GA Google plugin.

Using in this configuration I can confirm basic tracking is working ok - I can see stats coming through

---

If I [enable debugging mode](https://developers.google.com/analytics/devguides/collection/analyticsjs/debugging) in the Woo plugin I can see the second version of the GA script is not initialized which is correct

![Screen Shot 2020-11-02 at 1 13 28 pm](https://user-images.githubusercontent.com/355014/97825926-0544a880-1d10-11eb-9501-9751468761b0.png)

I can see events are still fired off and that the ec: events events/attributes/impression ([reference](https://developers.google.com/analytics/devguides/collection/analyticsjs/enhanced-ecommerce))

![Screen Shot 2020-11-02 at 1 31 30 pm](https://user-images.githubusercontent.com/355014/97826132-b0edf880-1d10-11eb-9af2-b82bbcc44d00.png)
 are being fired off

I tried disabling the WooCommerce standard tracking as described and the events are still being triggered in the debugging code without any errors.

---

In the GA interface, I can see events gradually populating

![Screen Shot 2020-11-02 at 1 57 06 pm](https://user-images.githubusercontent.com/355014/97827145-586c2a80-1d13-11eb-9126-f2aea2740f8d.png)

But nothing yet under conversions ecommerce

I'll check back in a day or two to see if anything changes

---

I can see puchase EC events as well being sent

![Screen Shot 2020-11-02 at 1 59 51 pm](https://user-images.githubusercontent.com/355014/97827306-c87ab080-1d13-11eb-9291-e250ba7993aa.png)

**Comment by findingsimple** [comment]
@NathanaelServiceCompany its been a while - can you confirm if you have any new information about your experience here?

**Comment by findingsimple** [comment]
> I'll check back in a day or two to see if anything changes

Just checked and the ecommerce stats have started appearing

![Screen Shot 2020-11-03 at 12 34 39 am](https://user-images.githubusercontent.com/355014/97877143-af521e00-1d6c-11eb-9055-6b01183a86f2.png)

![Screen Shot 2020-11-03 at 12 37 36 am](https://user-images.githubusercontent.com/355014/97877252-cd1f8300-1d6c-11eb-99e1-6bd312138844.png)

Everything seems as expected.
