### ISSUE TITLE
Filter needed to modify transaction data

### ISSUE THREAD

**Issue by ajayghaghretiya-multidots** [woocommerce/woocommerce-google-analytics-integration#171]
#### What I expected

We have modification data for the product on our website and we need to track all the custom information on Google Analytics Tools. We are using this plugin. And it did very much help with that. 

But It would be really great we have some control on data when calling any transaction event. And we all know the modification in the plugin is not a good thing.

So If we have some filters to modify the data from the theme that will be very helpful.

Also, GA supporting more fields https://developers.google.com/analytics/devguides/collection/analyticsjs/enhanced-ecommerce#product-data but we don't have filter to add the fields & it's data.

#### What happened instead
Don't have any filter to modify the enhanced purchase transaction data of the Order's item.

We have limited static fields for the enhanced purchase transaction in the path **_woocommerce-google-analytics-integration/includes/class-wc-google-analytics-js.php_**

                `function add_item_enhanced( $order, $item ) {
		$_product = version_compare( WC_VERSION, '3.0', '<' ) ? $order->get_product_from_item( $item ) : $item- 
                >get_product();
		$variant  = self::product_get_variant_line( $_product );

		$code = "" . self::tracker_var() . "( 'ec:addProduct', {";
		$code .= "'id': '" . esc_js( $_product->get_sku() ? $_product->get_sku() : $_product->get_id() ) . "',";
		$code .= "'name': '" . esc_js( $item['name'] ) . "',";
		$code .= "'category': " . self::product_get_category_line( $_product );

		if ( '' !== $variant ) {
			$code .= "'variant': " . $variant;
		}

		$code .= "'price': '" . esc_js( $order->get_item_total( $item ) ) . "',";
		$code .= "'quantity': '" . esc_js( $item['qty'] ) . "'";
		$code .= "});";

		return $code;
	} `

#### Steps to reproduce the issue
1. If you have brand specified on the site via product tag or any custom field. It will not log to GA with the field while GA supporting that field.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by mikkamp** [comment]
Thanks for providing a suggested PR. It's a nice solution but we are going to need a more standardized approach for adding hooks to the various snippets which are output.

In the PR a filter is being added for the `ec:addProduct` event on the thank you page. However this event is recorded in many different locations throughout the code. So it would be best to use a set of standard filters so all locations can be hooked into. Creating an array for the variables does make it easier to filter, but doesn't work in all cases (like the ones where the values are set through jQuery).

We would have to look further into what would be the best solution for all cases. So at the moment we will leave this issue open as an enhancement so it can be prioritized correctly.

**Comment by martynmjones** [comment]
Hey @ajayghaghretiya-multidots 👋

A recent update to the extension [introduced a filter](https://github.com/woocommerce/woocommerce-google-analytics-integration/blob/1cf0d278ff8835267b4092688632eb494f68ce4c/includes/class-wc-google-gtag-js.php#L106) `woocommerce_gtag_event_data` which will allow modification of event data. This will be included in this weeks release of the extension.

**Comment by ajayghaghretiya-multidots** [comment]
Okay, This is great news, It would help the developer to modify the google tag data.
