### ISSUE TITLE
Google Analytics 4

### ISSUE THREAD

**Issue by dougaitken** [woocommerce/woocommerce-google-analytics-integration#173]
There is [a big update to Google Analytics](https://blog.google/products/marketingplatform/analytics/new_google_analytics/) and one "small" changes is the tracking ID format. Our friends over at WordPress.com have some changes needed - p58i-9Dr-p2 - helpful screenshots included.

I imagine this will change how the GA plugin also works/understands what is a valid tracking ID so I'm opening this issue to get this checked over.

Slotting this as "bug" for now.

**Comment by findingsimple** [comment]
Thanks @dougaitken for the reference link. We'll likely be tackling this with some larger changes.

**Comment by bloukingfisher** [comment]
I've setup a new site with a new GA4 (Google Analytics 4) implementation with WooCommerce and WooCommerce Google Analytics Integration. Using the G- code (there is no UA- code available) it doesn't end up tracking any e-commerce events. 

I'm not sure if there are workaround options to get it to work. 
It will also require updating instructions (e.g.; as far as I can tell options such as "enabling ecommerce tracking" is not applicable any longer and happens automatically).

**Comment by findingsimple** [comment]
Hi @bloukingfisher 👋 

> Using the G- code (there is no UA- code available)

That's correct, if you follow the default prompts when setting up a new Google account you will only get a GA4 property with a measurement ID.

During property set up if you "Show Advanced Options"  you can toggle option to choose whether to create both a GA4 property AND a UA property or just a UA property e.g.

![Screen Shot 2020-10-29 at 12 20 36-fullpage](https://user-images.githubusercontent.com/355014/97515968-0dd07280-19e2-11eb-920b-df174b1b8428.png)

> I'm not sure if there are workaround options to get it to work.

I'm investigating options at the moment. For now, GA4 properties simply are not supported by the extension.

> It will also require updating instructions (e.g.; as far as I can tell options such as "enabling ecommerce tracking" is not applicable any longer and happens automatically).

For UA and classic property it is still an option e.g.

![Screen Shot 2020-10-29 at 12 29 36-fullpage](https://user-images.githubusercontent.com/355014/97516220-94854f80-19e2-11eb-8188-a399bcae8e0c.png)

For GA4 properties, that is correct - there is no specific option for enabling ecommerce tracking.

---

Using the intended UA property tracking, everything should still work as expected (this is just some of the live view data from a brand new test site)

![Screen Shot 2020-10-29 at 12 40 54-fullpage](https://user-images.githubusercontent.com/355014/97516911-175ada00-19e4-11eb-9895-43e242b406da.png)

**Comment by ghost** [comment]
Hi,
Is there an expected date available for the solution?

**Comment by findingsimple** [comment]
None available at the moment sorry @michavandijk

**Comment by michaloo** [comment]
EDIT: I was wrong (see below) :)


￼￼Since this is not supported here yet, just wanted to give a hint that alternatively, you could integrate WooCommerce with GA4 using Google Tag Manager and this plugin:

https://woocommerce.com/products/google-tag-manager-for-woocommerce-pro/

**Comment by dougaitken** [comment]
@michaloo GA4 is supported now. The linked PR above has the details #176 - https://github.com/woocommerce/woocommerce-google-analytics-integration/blob/trunk/changelog.txt :)

**Comment by michaloo** [comment]
@dougaitken thanks for pointing it out. I see it's already there for a while (since Dec 2020). Sorry for not verifying my comment, I have updated it :)
