### ISSUE TITLE
Ecommerce data not tracked after Site Kit has been active

### ISSUE THREAD

**Issue by dougaitken** [woocommerce/woocommerce-google-analytics-integration#178]
#### What I expected

When using the [Google Site Kit](https://wordpress.org/plugins/google-site-kit/) plugin along with this integration, I can have standard site tracking via Site Kit and eCommerce tracking via the Google Analytics Integration

#### What happened instead

When Google Site Kit is active, visits are tracked as expected but eCommerce data is not tracked. 

#### Steps to reproduce the issue

Install the needed plugins:
* WooCommerce
* Google Site Kit
* Google Analytics Integration
* A payment gateway that redirects to the `order-received` page (I'm using [Stripe](https://woocommerce.com/products/stripe/))

Follow the [WooCommerce Google Analytics Documentation](https://docs.woocommerce.com/document/google-analytics-integration) for setup instructions and uncheck Standard Tracking.

Place orders via test accounts and a multitude of browsers - I used Safari, Google Chrome, Chrome on Android, and Firefox over the course of my testing.

When the Site Kit plugin is active, no e-commerce tracking is shown. To be clear, all other tracking shows such as Real Time and historical tracking in Audience Overview. 

It seems the timing of Forum postings and my testing comes related to Google Analytics 4 - #173 - the code I've been using was generated some time ago.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by findingsimple** [comment]
Marking as a bug and with high priority for further investigation - we can adjust once we know some more. 

I'm not sure what type of tracking SiteKit is using. 

From https://github.com/woocommerce/woocommerce-google-analytics-integration/issues/167 I think e-commerce tracking should work with Standard tracking disabled but its possible there is a mismatch in the type of GA tagging being used. 

@dougaitken do you know what type of tagging SiteKit is implementing on your site? If you have a test site you are seeing this on that could be useful as well.

cc @layoutd

**Comment by dougaitken** [comment]
Hey @jconroy I was going to test 1.5 on my core test site but you can use this if needed? `https://core.doug.press` - let me know if and how you want to access and I can add people as needed to that and the Google Analytics account

**Comment by findingsimple** [comment]
Heya @dougaitken thanks for that. It looks like it is using gtag.js (just looking at the source) - so as-is (pre a 1.5 release) that wouldn't work because the main tracking code in sitekit is gtag.js (we don't support that) and the Woo GA plugin would be trying to send events using analytics.js (or legacy ga.js)

Post 1.5, it's something we'd need to check - so I'll think I'll mark this as an enhancement and we'll look at it while we are going with the 1.5 testing (this week - I actually spent a bunch of time on it today)

**Comment by findingsimple** [comment]
Chatting with @layoutd some more on this, my understanding might be flawed. @layoutd is going to double check

**Comment by findingsimple** [comment]
I've done a bunch of testing with the 1.5 release candidates and the e-commerce tracking seems to be ok

![Screen Shot 2020-12-16 at 2 30 12 pm](https://user-images.githubusercontent.com/355014/102307521-91571a80-3fb4-11eb-892c-98afc7445cc5.png)

![Screen Shot 2020-12-16 at 2 29 24 pm](https://user-images.githubusercontent.com/355014/102307543-9a47ec00-3fb4-11eb-86ef-ea72dd5574de.png)

![Screen Shot 2020-12-16 at 2 29 05 pm](https://user-images.githubusercontent.com/355014/102307620-c9f6f400-3fb4-11eb-91fc-f317aceb0702.png)

![Screen Shot 2020-12-16 at 2 28 41 pm](https://user-images.githubusercontent.com/355014/102307651-d4b18900-3fb4-11eb-8189-242cf83225e0.png)

**Comment by dougaitken** [comment]
Yes, I retested this as part of the 1.5.0 testing and @layoutd's release fixes my previous issues 🥳 :shipit:
