### ISSUE TITLE
WC 5.0 - Increase tested up to tags

### ISSUE THREAD

**Issue by findingsimple** [woocommerce/woocommerce-google-analytics-integration#180]
WooCommerce 5.0 is currently scheduled for release on February 9th.

With 5.0, WooCommerce is moving to WP versioning and 5.0 is no longer considered to include breaking changes.

Prior to 4.9.2, WooCommerce included a number of extra warnings to prep users for a major change. These are no longer necessary.

If WooCommerce users upgrade to 5.0 from a version prior to 4.9.2 they would still see these warnings.

To help avoid confusion and smooth the process we should be sure to perform the following...
* [x] Quick smoke test of functionality (review docs for functionality and intended usage)
* [x] Increase tested up to tags
* [x] Create follow-up issues for anything that needs to be fixed/investigated (or simply fix) - generally we should be fine, the compact checks have come back ✅

**Comment by haszari** [comment]
I've pushed the `Tested up to` change direct to trunk: 4912228

Testing …

Test setup:

- Release WordPress 5.6.
- Active plugins: WooCommerce 5.0.0-rc.1, WooCommerce Stripe Gateway 4.8.0.
- Theme: Twenty Twenty-One 1.1.
- Dev build of Woo core `5.0.0-rc.2` [tag](https://github.com/woocommerce/woocommerce/releases/tag/5.0.0-rc.2).
- Dev build of extension trunk.

**Comment by haszari** [comment]
Tested using the [web version of **Google Tag Assistant**](https://tagassistant.google.com/) - the [chrome extension](https://chrome.google.com/webstore/detail/tag-assistant-legacy-by-g/kejbdjndbnbjgmefkgdddjlbokphdefk/related) seems to be broken/out of date.

I set up a fake / dev test analytics property, configured the tracking ID in the plugin settings, and wahey it seems to be recording stuff:

<img width="939" alt="Screen Shot 2021-02-03 at 12 51 02 PM" src="https://user-images.githubusercontent.com/4167300/106678043-c419a880-661e-11eb-9050-6451a26388d4.png">

So this is good to go 👍
