### ISSUE TITLE
Issue with UTM_override code

### ISSUE THREAD

**Issue by melindahelt** [woocommerce/woocommerce-google-analytics-integration#181]
I received a chat where user was passing along information from Google regarding the use of our plugin. I attempted to get more information, but they would not provide anything other than what is listed here. Google told them to have us remove this code from the plugin. I'm not sure if that is possible, but we'll need to follow up.

>We are having an issue with our Woo store not tracking our UTM codes or sources on Google. I spent a LOT of time with Google making sure that our codes on our website as well as our GA were set up properly and everything is. They said to reach out to you.

>What is happening is the Woo platform is adding a "UTM_override" code to our checkout page, making the source of our traffic and purchases all register as DIRECT traffic, even if they are coming from social. I reached out to both PayPal and STRIPE and they said that they need Woo to sort this out.

>Here is the reply from Google:

>We analyzed the traffic on your website and we noticed that there are no issues with Analytics tracking. On the last step after they complete the payment, they are being treated as direct traffic and the reason for this is utm_nooverride=1. utm_nooverride=1 is a parameter that you attach to your payment gateway return pages. Say your return page is /checkout/payment/success. You need to provide this URL to your payment gateway: /checkout/payment/success?utm_nooverride=1 . This way Google will ignore the referrer information for this session if there is already another session in progress. Here, the referrer information like facebook, google cpc, instagram will be overridden by this parameter to direct.

>Please remove this parameter and your issue should be resolved. Please let us know if you have any questions or need any other assistance before we close this case.

**Comment by melindahelt** [comment]
3705896-zen

**Comment by kristenzuck** [comment]
The above customer reached out again looking for an update. I've said that we don't have any new information, but we'll be in touch once we do.

**Comment by findingsimple** [comment]
Just adding a note to look at https://github.com/woocommerce/woocommerce-google-analytics-integration/blob/trunk/includes/class-wc-google-analytics.php#L96

**Comment by layoutd** [comment]
Hi @melindahelt & @kristenzuck,

Thanks for the report. As @jconroy astutely observed, the `utm_nooverride` parameter is added to the return page URL by the WooCommerce Google Analytics Integration extension during checkout.

One quick solution that may work for the user would be to add this filter which simply removes the parameter again:
```php
add_filter( 'woocommerce_get_return_url', function($return_url) { 
	return remove_query_arg( 'utm_nooverride', $return_url );
}, 11);
```

If this solves the user's issue, please let us know so that it can be added  to the [extension documentation](https://docs.woocommerce.com/document/google-analytics-integration/#disabling-pageview).

**Comment by findingsimple** [comment]
Going to close until we hear something back.
