### ISSUE TITLE
Tweak settings for new woo nav

### ISSUE THREAD

**Issue by haszari** [woocommerce/woocommerce-google-analytics-integration#183]
Issue covering all changes needed to work well in [new WooCommerce Admin nav](https://developer.woocommerce.com/2021/01/15/call-to-action-create-access-for-your-extension-in-the-new-woocommerce-navigation/).

Google Analytics has a settings page, which is accessible under `WooCommerce > Settings > Integration(s) > Google Analytics`. This is working fine in the new nav, though it may be more consistent to move this settings page under `WooCommerce > Extensions > Google Analytics` since it's an extension (not part of woo core).

<img width="1197" alt="Screen Shot 2021-02-17 at 2 33 11 PM" src="https://user-images.githubusercontent.com/4167300/108143829-521c8580-712d-11eb-8236-e14ad5a2b6ea.png">

**Comment by mikkamp** [comment]
Closing this issue as the "new woo navigation" project is not being worked on and has been disabled: https://github.com/woocommerce/woocommerce/issues/35157

We can reopen again if there are further changes.
