### ISSUE TITLE
GA4 Adding duplicate tags on the website

### ISSUE THREAD

**Issue by steven-hardy** [woocommerce/woocommerce-google-analytics-integration#184]
#### What I expected

The GA4 tag to be called only once on the page.

#### What happened instead

This is currently being called twice and is causing duplicate reporting in Google Analytics.

#### Steps to reproduce the issue

I have added the plugin to a website and now the code is duplicated in the head of the website. 

![woo-ga](https://user-images.githubusercontent.com/50919787/108493237-ff161000-729d-11eb-9221-d20fe3bb614d.jpg)

We are using the GA4 part of the plugin.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by budzanowski** [comment]
Hello @steven-hardy 

I can't really reproduce this problem. Are you using any other Google Analytics Plugins? And what do you mean exactly by:
> We are using the GA4 part of the plugin.

?

**Comment by steven-hardy** [comment]
Hello @budzanowski 
Thank you for your reply.

I actually forgot to comment here and say that it was resolved. I believe that the theme that we was using had the tag and then the plugin was adding the tag too. So I removed the theme one, and its all ok now :) I will close this issue.
