### ISSUE TITLE
Incompatibility with Google Product Feed (Ademti)

### ISSUE THREAD

**Issue by haszari** [woocommerce/woocommerce-google-analytics-integration#187]
User is running both [Google Analytics](https://woocommerce.com/products/woocommerce-google-analytics/) and [Google Product Feed](https://woocommerce.com/products/google-product-feed) on their site. 

This causes a `Product ID` mismatch error. Google Analytics passes only the product ID; Google Product Feed prefixes product ID with `woocommerce_gpf_prefix`. 

Originally raised by @yukikatayama 

#### What I expected
Can use both Google Analytics and Google Product Feed on same site without errors.

#### What happened instead

TBC - (@haszari has not reproduced this issue)

#### Steps to reproduce the issue

TBC

##### Possible fixes
- Add support in GA plugin for prefixing the product ID so they match (e.g. a UI option or filter).

**Comment by haszari** [comment]
One thing that I don't understand - should the product IDs be consistent across both plugins, or should they be unique? 

If they need to be consistent then this might be more complex (especially if there are other plugins that use same ID with Google APIs).

**Comment by haszari** [comment]
Marked as `low` for now since we haven't seen many reports of this. If it's affecting more merchants can bump the priority.

**Comment by leewillis77** [comment]
Hi; 

I'm the developer of the Google Product Feed plugin. For info, I'm planning on opening a PR to make the information output by this extension filterable so that other plugins can modify / add to it as required, but it'll likely be a week or two before we can look at it.

**Comment by haszari** [comment]
Thanks @leewillis77 !

**Comment by martynmjones** [comment]
The product identifier can now be filtered using `woocommerce_ga_product_identifier` which should address the issue described here and other potential mismatches so closing issue.
