### ISSUE TITLE
Product prices with taxes

### ISSUE THREAD

**Issue by rolandso** [woocommerce/woocommerce-google-analytics-integration#191]
Why are the product prices in google analytics without taxes?
When user completes the order, the product price is shown with a tax, but in google analytics it shows the product price without a tax.

**Comment by budzanowski** [comment]
Hello,

In the Plugin [documentation](https://docs.woocommerce.com/document/google-analytics-integration/), you can find the following:

> Purchase Transactions: Track purchases on your site, including data like revenue, tax, refunds, shipping, and more. This requires a payment gateway that redirects to the thank you/order received page after payment. Some popular options that do this are Stripe, Braintree for WooCommerce, PayPal Checkout, and Square.

If this does not help please create an issue with the exact reproduction steps and include system status request: https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/
