### ISSUE TITLE
Google Analytics: Price amount is not tracked : Please Help Us

### ISSUE THREAD

**Issue by AdityaMindatrafik** [woocommerce/woocommerce-google-analytics-integration#192]
Thanks for your Time 

We need help,  Google Analytics: Price amount is not tracked

Here are the details:

https://www.farmasicolourcosmetics.com
WP: Current version: 5.7.2
WooCommerce Plugin: 5.3.0
WooCommerce Google Analytics Integration Plugin: 1.5.1
Currency used = MYR

GA its always '0' at the revenue..

![image](https://user-images.githubusercontent.com/85553826/121170734-cff0d200-c87f-11eb-8f36-fca79cc2980e.png)

**Comment by budzanowski** [comment]
While looking at your site I can see that it is not configured correctly. I can see that you are using at least Google Analytics plugins ( or the tracking code was added manually ). This most probably breaks the configuration:
![image](https://user-images.githubusercontent.com/17271089/133053433-a9964324-c12a-4f91-9e79-cf333db8adb3.png)

The first two tags look like they are correct (the same id number). But the third one is wrong and gives an error. I can't see from the screenshot id you are tracking.

Google gives some advice on that https://support.google.com/analytics/answer/1032400

I would start by making sure that there are no google analytics plugins and manual tags installed and then I would set the integration using the correct id using the information from the documentation https://docs.woocommerce.com/document/google-analytics-integration/

Which tags are used on a particular page an which events are triggered can be observed using this Chrome https://chrome.google.com/webstore/detail/tag-assistant-legacy-by-g/kejbdjndbnbjgmefkgdddjlbokphdefk

I am sure that cleaning up the configuration will solve the problem. If not please fill in an issue with clear reproduction steps.
