### ISSUE TITLE
Update GA Pro utm link 

### ISSUE THREAD

**Issue by findingsimple** [woocommerce/woocommerce-google-analytics-integration#194]
We've been asked to standardize UTM tags point to WCCOM - specifcally to standardize on using

`utm_medium=product`

GA has an upsell notice pointing merchants to WCCOM here which uses `utm_medium=upsell`

https://github.com/woocommerce/woocommerce-google-analytics-integration/blob/trunk/woocommerce-google-analytics-integration.php#L144

We need to update the link.

> https://woocommerce.com/products/woocommerce-google-analytics-pro/?utm_source=product&utm_medium=upsell&utm_campaign=google%20analytics%20free%20to%20pro%20extension%20upsell

I don't think it makes sense to use both

`utm_source=product`
`utm_medium=product`

So I think we should also change `utm_source` to be `utm_source=woocomerce-google-analytics-integration`

i.e. use the product slug

Change to

> https://woocommerce.com/products/woocommerce-google-analytics-pro/?utm_source=woocomerce-google-analytics-integration&utm_medium=product&utm_campaign=google%20analytics%20free%20to%20pro%20extension%20upsell

Internal reference p6q6po-bHk-p2 asking teams to standardize UTM tags

**Comment by ecgan** [comment]
> So I think we should also change `utm_source` to be `utm_source=woocomerce-google-analytics-integration`

@jconroy, I believe there is an unintentional typo (missing an `m` in `woocomerce`), I'll change it to `utm_source=woocommerce-google-analytics-integration`.

**Comment by findingsimple** [comment]
@ecgan good catch, definitely a typo
