### ISSUE TITLE
Trying to access array offset on value of type null

### ISSUE THREAD

**Issue by michaldusek** [woocommerce/woocommerce-google-analytics-integration#199]
Notice: 
Trying to access array offset on value of type null in .../plugins/woocommerce-google-analytics-integration/includes/class-wc-google-analytics.php on line 572  
Notice: Trying to access array offset on value of type null in .../plugins/woocommerce-google-analytics-integration/includes/class-wc-google-analytics.php on line 585

Using WP Woocommerce, Template Avada and their product slider (www.michaljezek.cz)

If user is logged to WP, it is clear (without Notice)

**Comment by findingsimple** [comment]
Hi

Possibly related to the `woocommerce_loop` global - perhaps Avada does something custom with it.

> Template Avada and their product slider (www.michaljezek.cz)

Would be nice to do some conflict testing @michaldusek and check if you still see the issue when using a theme like storefront

> If user is logged to WP, it is clear (without Notice)

it's likely just because the extension doesn't add tracking for admins.

**Comment by mikkamp** [comment]
Haven't got any feedback after suggesting conflict testing, and no additional reports.
The [line of code](https://github.com/woocommerce/woocommerce-google-analytics-integration/blob/1.5.3/includes/class-wc-google-analytics.php#L585) that triggered the error, is only used in Universal Analytics implementation (which is going to be retired by Google by 1st of July), so the scope is limited.

Closing the issue for now, but feel free to reopen if there are additional reports.
