### ISSUE TITLE
Inconsistent names for variable products

### ISSUE THREAD

**Issue by aheckler** [woocommerce/woocommerce-google-analytics-integration#200]
#### What I expected

Variable product names to be consistent in Google Analytics through the purchase process, i.e. on whether the variation attributes are included in the name.

#### What happened instead

Add to Cart:

`{items: [{id: "#53", name: "Variable Product", quantity: "1"}]}`

Checkout:

`{items: [{id: "#57", name: "Variable Product", category: "Uncategorized", variant: "size: Medium, color: Red", price: "32", quantity: "3"}]}`

Purchase:

`{items: [{id: "57", name: "Variable Product - Medium, Red", category: "Uncategorized", variant: "size: Medium, color: Red", price: "32", quantity: "3"}]}`

Notice how the variant details are included in the name in the Purchase, but not in others? Seems inconsistent, and might cause awkward looking data in GA.

#### Steps to reproduce the issue

I had trouble getting GA set up correctly to repro this, so @layoutd helped me out in Slack, and directed me here.

Originally brought up in this forums thread:

https://wordpress.org/support/topic/attributes-difference-between-addtocart-and-purchase/?view=all

... and discussed in Slack here:

p1633008284044100-slack-C7U3Y3VMY

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by layoutd** [comment]
Leaving this as low priority for the moment.
