### ISSUE TITLE
When used with WC google-analytics-integration, the Google Analytics script is loaded twice

### ISSUE THREAD

**Issue by laurentdebricon** [woocommerce/woocommerce-google-analytics-integration#212]
Hello, 
i have https://github.com/woocommerce/woocommerce-google-analytics-integration
and now with your plugin, i have two requests to google analytics :
![Screenshot from 2021-12-03 15-56-08](https://user-images.githubusercontent.com/736104/144623518-e8aed987-dc37-490e-8224-6858aa777776.png)

it seems that 
```
if ( ! wp_script_is( 'google-tag-manager', 'registered' ) ) {
```
is a great check but it is missing in woocommerce-google-analytics-integration , which comes after on my screenshot.
could you talk to each other and make both script from the same corporation behave together ?

thank you !

**Comment by syntaxerror** [comment]
> From what I can see, having the duplicate script does not break tracking in any way

Sorry to say, but it does indeed break the page view tracking. Page views will only show up in GA4 after disabling the ' Add to Cart Events' option, but then we do loose that tracking instead...

Ref https://github.com/woocommerce/woocommerce-blocks/blob/trunk/src/Domain/Services/GoogleAnalytics.php#L56-L79

**Comment by Babylon1999** [comment]
Hey everyone,

This seems to be affecting the real-time page views as mentioned by @syntaxerror and in zd-5980880.

I went ahead and advised them to turn off the Add-to-cart events for now, but that doesn't seem like a solid solution.

**Comment by jakewhiteley** [comment]
This issue has been going on for  2 years now, and is even more prevalent with the forced switch to GA4 as your plugin does not track page views/page titles correctly.

Telling people to turn off "add to cart" events or to modify the plugin code themselves is not an option.

**Comment by fdmsaraiva** [comment]
The title of this issue does not reflect the severity of the issue.

“_**When used with WC google-analytics-integration, the Google Analytics script is loaded twice**_” identifies the cause, however, causes don’t define priorities, consequences do.

Suggest renaming the title to something like “**_Add to Cart option breaks page view tracking_**“ so it identifies the consequence.

**Comment by onasipim** [comment]
It still doesn't work and I have to manually edit the file wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/Domain/Services/GoogleAnalytics.php:77 and set send_page_view to true

**Comment by puntope** [comment]
> It still doesn't work and I have to manually edit the file wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/Domain/Services/GoogleAnalytics.php:77 and set send_page_view to true

Howdy @onasipim 

To clarify, with "doesn't work" do you mean the Google Tag Manager script is still loaded twice on your site? 

If so might you provide more information? I was not able to reproduce the duplication on my site.

**Comment by onasipim** [comment]
I have installed WooCommerce Google Analytics Integration and connected it with my G-XXX tracking id, all options activated incl. add to cart. 

Additionally these two but without any Google tracking so they shouldn't interfere:
- Rank Math SEO
- Google Listings and Ads

Now the website adds the tracking code, but with send_page_view to false, therefore no tracking happens. Only when I manually set it to true in the block code wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/Domain/Services/GoogleAnalytics.php:77 it works. Seems like the block tracking code interferes with the regular tracking snippet.

**Comment by puntope** [comment]
So can you verify that you only have one script only for `google-tag-manager`? 

Also, can you send us a screenshot of the code in the `google-tag-manager-js` block? It seems to me that `wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/Domain/Services/GoogleAnalytics.php` is being loaded but that shouldn't be the case.  

Could yo also send us te version of WooCommerce Google Analytics Integration you're using?
