### ISSUE TITLE
Universal Analytics will stop processing data on July 1, 2023

### ISSUE THREAD

**Issue by layoutd** [woocommerce/woocommerce-google-analytics-integration#215]
Google Analytics will no longer collect Universal Analytics data starting on July 1, 2023. As per <https://support.google.com/analytics/answer/11583528>:
> ### Universal Analytics will be going away
> _Last updated: March 16, 2022. Visit this page in the coming months for the latest information._
> - Until July 1, 2023, you can continue to use and collect new data in your Universal Analytics properties.
> - After July 1, 2023, you'll be able to access your previously processed data in your Universal Analytics property for at least six months. We know your data is important to you, and we strongly encourage you to [export](https://support.google.com/analytics/answer/11583528#export) your historical reports during this time.
> - In the coming months, we'll provide a future date for when existing Universal Analytics properties will no longer be available. After this future date, you'll no longer be able to see your Universal Analytics reports in the Analytics interface or access your Universal Analytics data via the API.

**Short Term**
It may make sense to include a notice for users that are currently using a Universal Analytics property in the coming months, so they have time to migrate if desired.

**Long Term**
Refactor/disable/remove functionality associated with Universal Analytics.

**Comment by layoutd** [comment]
Postponing this until changes are about 12 months out, with the idea to add dismissible alerts (for affected users), and then permanent alerts immediately before the changes become effective.

**Comment by strarsis** [comment]
@layoutd: But WooCommerce Google Analytics would work/continue working with the new Google Analytics 4, right?

**Comment by layoutd** [comment]
Hi @strarsis, yes, GA4 will continue to be supported, but users still on Universal Analytics will be prompted to upgrade to GA4 (manually) or lose functionality.
