### ISSUE TITLE
Include more than one tracking ID Not working

### ISSUE THREAD

**Issue by haspden** [woocommerce/woocommerce-google-analytics-integration#226]
issue with

Include more than one tracking ID
https://woocommerce.com/document/google-analytics-integration/#disabling-pageview

I've added to my functions.php file

```
add_filter( 'woocommerce_gtag_snippet', function( $gtag_snippet ) {
	return preg_replace( '~</script>~', "gtag('config', 'UA-ABC123-13');\n</script>", $gtag_snippet );
} );
```

However the additional UA is not included in the source code

```
<!-- WooCommerce Google Analytics Integration -->
--
  | <script type='text/javascript'>
  | var gaProperty = 'UA-ABD999-5';
  | var disableStr = 'ga-disable-' + gaProperty;
  | if ( document.cookie.indexOf( disableStr + '=true' ) > -1 ) {
  | window[disableStr] = true;
  | }
  | function gaOptout() {
  | document.cookie = disableStr + '=true; expires=Thu, 31 Dec 2099 23:59:59 UTC; path=/';
  | window[disableStr] = true;
  | }
  | </script><script type='text/javascript'>(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]\|\|function(){
  | (i[r].q=i[r].q\|\|[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  | m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  | })(window,document,'script', '//www.google-analytics.com/analytics.js','ga');ga( 'create', 'UA-ABC999-5', 'auto', { allowLinker: true });(window.gaDevIds=window.gaDevIds\|\|[]).push('dOGY3NW');ga( 'require', 'displayfeatures' );ga( 'require', 'linkid' );ga( 'set', 'anonymizeIp', true );
  | ga( 'set', 'dimension1', 'no' );
  | ga( 'require', 'ec' );ga( 'require', 'linker' );ga( 'linker:autoLink', ["url.co.uk","url2.co.uk","url3.co.uk","book.url.co.uk","book.url2.co.uk","book.url3.co.uk"]);</script>
  | <!-- /WooCommerce Google Analytics Integration -->
```

**Comment by findingsimple** [comment]
Hi @haspden I've tagged as a question, one of the devs might be able to investigate quickly for you in the coming weeks - however to set expectations, we don't use Github for support questions/requests and I would recommend contacting WooCommerce.com support directly as our happiness team might be able to offer assistance more quickly.

**Comment by budzanowski** [comment]
Hi @haspden,

The code you are using should work. 
Please make sure that there are no other Google Analytics plugin enabled as this may cause issues with the integration.
Another thing to check is if you are using the correct functions.php file. For example if this file is located in a theme that is not loaded this snippet will not work.

**Comment by mikkamp** [comment]
I'm closing this issue now, as mentioned above the code should work as is. We haven't had any feedback since then, but let us know if there is any followup to this issue.
