### ISSUE TITLE
Cannot hide prices on B2B websites

### ISSUE THREAD

**Issue by seldimi** [woocommerce/woocommerce-google-analytics-integration#247]
There is no way to remove the javascript price tag, if WooCommerce store is B2B only, we need to hide prices for non logged in. We usually do this via "woocommerce_get_price_html" but this doesn't work here. 
Currently, if you hit "view-source", you can see the price

Modifying woocommerce_get_price is risky, as its used internally for many other things. 

I suggest a apply_filters to be added somewhere near:
https://github.com/woocommerce/woocommerce-google-analytics-integration/blob/3ef4af09237189556eb740b42ab6e3e943da3df8/includes/class-wc-google-gtag-js.php#L242

**Comment by martynmjones** [comment]
Hey @seldimi 👋 

A recent update to the extension [introduced a filter](https://github.com/woocommerce/woocommerce-google-analytics-integration/blob/1cf0d278ff8835267b4092688632eb494f68ce4c/includes/class-wc-google-gtag-js.php#L106) `woocommerce_gtag_event_data` which will allow modification of event data and removal of pricing information if required. This will be included in this weeks release of the extension so I'm marking this issue as closed for now. Thanks for the suggestion!

**Comment by seldimi** [comment]
Hello. When this release is about to be?

**Comment by martynmjones** [comment]
@seldimi Version `1.6.0` was released on the 31st of January which includes the filter mentioned above.

**Comment by seldimi** [comment]
I didn't quite understood the filter as even if I pass an empty array, all these are still printed:

https://github.com/woocommerce/woocommerce-google-analytics-integration/blob/14fefc8758bcee573199b3a63626badb59800853/includes/class-wc-google-analytics-js.php#L421

**Comment by seldimi** [comment]
I didn't quite understood the filter as even if I put this on functions.php

```
add_filter( 'woocommerce_gtag_event_data', function($data){
    error_log($data);
    return [];
});
```

These are still printed
https://github.com/woocommerce/woocommerce-google-analytics-integration/blob/14fefc8758bcee573199b3a63626badb59800853/includes/class-wc-google-analytics-js.php#L463

**Comment by martynmjones** [comment]
> I didn't quite understood the filter as even if I put this on functions.php

It looks like you're attempting to modify the data used by the Universal Analytics implementation. This filter is only available when using Google Analytics 4. Universal Analytics is [being dropped by Google](https://support.google.com/analytics/answer/11583528) so no new features will be added to this extension for it.

I recommend [upgrading your website to Google Analytics 4](https://woocommerce.com/document/google-analytics-integration/#setup-and-configuration) and then you will be able to filter event data.

**Comment by seldimi** [comment]
Yes I've understood but until July 2023, prices are still exposed on B2B websites.
