### ISSUE TITLE
Events stopped working with version 1.6.0

### ISSUE THREAD

**Issue by osirismqz** [woocommerce/woocommerce-google-analytics-integration#252]
### Describe the bug:
Visits tracking works but events stopped working. The plugin is throwing a javascript "$ undefined" error. Seems to be jQuery related.

Rolled back to version 1.5.19 and everything works as expected. No javascript errors.

### Additional details:
Plugin Version 1.6.0, WP version 6.1.1, WooCommerce Version 7.3.0

**Comment by martynmjones** [comment]
Hey @osirismqz,

Thanks for the report, however, testing version `1.6.0` on a site with a standard configuration of WooCommerce I'm not able to replicate the issue you're describing.

Please open a [thread on the support forum](https://wordpress.org/support/plugin/woocommerce-google-analytics-integration/) so our team can troubleshoot the problem with you and if needed this issue can be reopened at a later date.

**Comment by osirismqz** [comment]
Hi again,

I tried again. Rolled back to 1.5.19 and everything works fine. Upgraded to 1.6 and 1.6.1 and get the Unexpected identifier '$' error.

It seems that escaping (or not escaping, I'm not sure) the forward slash character on products with child categories is throwing the error.

This is on version 1.5.19
![image](https://user-images.githubusercontent.com/292415/220132616-b56704b4-bfb0-4b31-8a9b-ef0a645b5440.png)

Same page on version 1.6.1
![image](https://user-images.githubusercontent.com/292415/220133316-3c90014d-f7b7-40e1-a805-9fdce310442c.png)
