### ISSUE TITLE
Analytics not recording properly since updating to v1.7.0

### ISSUE THREAD

**Issue by glagonikas** [woocommerce/woocommerce-google-analytics-integration#263]
The latest version (1.7.0) seems to have affected tracking, as reported by others on different threads.

We've not had time to investigate much, so we reverted to the previous version which seems to have resolved the issue.

There are a number of reports on the [support forum](https://wordpress.org/support/plugin/woocommerce-google-analytics-integration/), all reporting the same issue and the solution is to revert to the previous version, however, those threads are marked as resolved by the support team and i don't see this reported on GitHub so I'd imagine nobody is looking at it.

Considering there have been at least 6 reports (ours included) about GA not tracking properly since v1.7.0 and keeping in mind many folks wouldn't have updated yet, won't have realised, or won't have bothered reporting, I think you should look into this seriously and treat it as an actual bug, rather than a possible misconfiguration.

some examples
- https://wordpress.org/support/topic/sales-are-not-recording-google-analytics/
- https://wordpress.org/support/topic/ga-quit-tracking-with-update-1-7-0/
- https://wordpress.org/support/topic/cannot-see-the-revenue-by-product-ga4/
- https://wordpress.org/support/topic/also-ecommerce-tracking-stopped-working-here/
- https://wordpress.org/support/topic/also-ecommerce-tracking-stopped-working-here/#post-16617365 (comment deleted by support)

**Comment by puntope** [comment]
Hello, thanks for informing about this bug. I can confirm the problem and we are already working on it.

**Comment by puntope** [comment]
Hello again. The fix was released today in v1.7.1. We tested it on our side but we would appreciate if you can confirm if this release solves your problem as you're a user impacted by the bug.

Thanks in advance

**Comment by glagonikas** [comment]
@puntope We upgraded to v1.7.1 shortly after you released it, but so far (two days later), we've not seen any transactions being recorded on GA.

Looking at the history, transactions have abruptly stopped since upgrading to v1.7.0 and haven't come back after upgrading to v1.7.1.

I'm not sure if this change has resolved the issue for others on the forum, but it doesn't appear to have solved our issue.

**Comment by glagonikas** [comment]
@puntope at least one more person saying v1.7.1 does not work for them https://wordpress.org/support/topic/sales-are-not-recording-google-analytics/#post-16656420

Update: they seem to have updated their reply and now say that's because of the way their gateway does not redirect to the correct page, so our issue is not as widespread I'd imagine?

Are there any known issues with caching, object cache, or any of the big payment gateways (Stripe/Braintree/etc?) or something we should be aware of or change?

I can't think of anything else that would cause this and our problems definitely started on v1.7.0 because transactions stopped when we updated, restarted when we reverted to the previous version and stopped again when we tried v1.7.0 and v1.7.1 again.

**Comment by glagonikas** [comment]
We think our problem is to do with dual tracking because GA4 seems to be receiving the purchases, but UA doesn't.

We use the code shown under [Include more than one tracking ID](https://woocommerce.com/document/google-analytics-integration/#disabling-pageview) in the plugin docs but it doesn't appear to work properly.

@puntope can you confirm if this snippet can still work after v1.7.x because it doesn't appear to work for us?

p.s. We've turned off Autoptimize in case it matters but didn't make any difference.
p.s.2 the anchor ID on the docs is incorrect and it uses `#disabling-pageview` instead of a unique one. Whoever added this snippet on the docs, probably copied and pasted the header of the previous element without updating the links, so it's not possible to link to the correct section.

I suspect our issue with dual tracking is caused by #260 and maybe @mikkamp saying we shouldn't be breaking compatibility with UA just yet, but i'm not sure that's the case?

**Comment by mikkamp** [comment]
@glagonikas From my understanding the tracking on your site is fully working with GA4, is that correct?

The code snippet for including more that one tracking ID would work if pageviews are set to be tracked for the second tracking ID. However it wouldn't trigger a second purchase event, as the plugin is only setup to trigger the GA4 purchase event.

Could you clarify which events you were previously seeing in Universal Analytics that are now no longer working? Also considering that Google is shutting down Universal Analytics completely on the 1st of June 2023, why is is still necessary to be tracking to both properties?

**Comment by puntope** [comment]
> We think our problem is to do with dual tracking because GA4 seems to be receiving the purchases, but UA doesn't.

Maybe you can send me your logs if your're ok with that (I normally use Google Analytics Debugger extension) when you complete an order with 1.7.x. and one with 1.6.x  So I can check and compare. 

If your'e using Automtimize or plugins that potentially move scripts from header to footer, etc. It might happen that some GA commands run in a bad timing since we use now enqueue scripts. This is likely unhappening in 1.6.x because the old code was echoing directly the code using `wp_head`
