### ISSUE TITLE
[Follow-Up] - Compatibility with GA4

### ISSUE THREAD

**Issue by puntope** [woocommerce/woocommerce-google-analytics-integration#268]
This issue is a follow-up for the related work in migrating the actions from WC Blocks to the extension.

However, GA4 did some changes that should be reflected in the code. 

GA4 drops the `event_category` and `event_label` structure in favor of individual parameters for each event. Ref: https://developers.google.com/analytics/devguides/collection/ga4/reference/events?client_type=gtag#view_item_list

_Originally posted by @martynmjones in https://github.com/woocommerce/woocommerce-google-analytics-integration/pull/264#discussion_r1177792610_

Another task is the one mentioned here https://github.com/woocommerce/woocommerce-google-analytics-integration/pull/264#discussion_r1177796264

And finally this one: https://github.com/woocommerce/woocommerce-google-analytics-integration/pull/264#discussion_r1177790632

⚠️  The standard plugin events (outside the actions) are also using the Universal format. So it will be needed to revisit that also.

**Comment by enneit** [comment]
So this project go to perfom actions with ga4 and will abandon universal? Right?

**Comment by puntope** [comment]
@enneit Correct, we already started an internal project in order to deprecate and remove all the Universal Analytics legacy code.

**Comment by puntope** [comment]
See also https://github.com/woocommerce/woocommerce-google-analytics-integration/issues/215

**Comment by martynmjones** [comment]
Closing as #322 has been merged.
