### ISSUE TITLE
Hook/filter to remove product microdata

### ISSUE THREAD

**Issue by paperplanefactory** [woocommerce/woocommerce-google-analytics-integration#271]
Hello,
since some WooCommerce installations use custom meta fields for product info - also for generating microdata snippet for products - is it possible to add an hook or filter to disable product microdata generated by WooCommerce Google Analytics Integration from being published in single product page?

**Comment by martynmjones** [comment]
Hey @paperplanefactory,

There's no specific hook or filter that will allow you to control the data that is output on single product pages, however, all [event data can be filtered](https://github.com/woocommerce/woocommerce-google-analytics-integration/blob/fbcf24f01d3767eb984fe46a0582a03b6216bad5/includes/class-wc-google-gtag-js.php#L126) or alternatively it would be possible to [unhook the action](https://developer.wordpress.org/reference/functions/remove_action/) used to add the [tracking code to single products](https://github.com/woocommerce/woocommerce-google-analytics-integration/blob/fbcf24f01d3767eb984fe46a0582a03b6216bad5/includes/class-wc-google-analytics.php#L100).

As it is possible to achieve this already I'm going to go ahead and close this issue. If you need any further assistance with the extension please open a request on the [support forum](https://wordpress.org/support/plugin/woocommerce-google-analytics-integration/).
