### ISSUE TITLE
Change to use wp_enqueue has made gtag.js load synchronously

### ISSUE THREAD

**Issue by WiredWonder** [woocommerce/woocommerce-google-analytics-integration#279]
### Describe the bug:
The commit made in https://github.com/woocommerce/woocommerce-google-analytics-integration/commit/730495a09bbb22798f897a64907ceeccf278dcb5#diff-75fada6b677c39f17a7de173a315db4d8911e7469f5a70dce4822a6aaa849514 has switched to loading gtag using wp_queue_script. Unfortunately this has meant gtag lost its async tag and is loading render blocking. Scores on Core Web Vitals show. 

### Steps to reproduce:
1. Upgrade to a version of the plugin post this commit
2. View source
3. gtag script has no async tag

### Expected behavior:
Tag should load async to improve Woocommerce performance

### Actual behavior:
Change regressed performance due to synchronous JS

### Additional details:
![image](https://github.com/woocommerce/woocommerce-google-analytics-integration/assets/1524468/cfae1bf2-6735-44c8-a7d7-e1294691f7fb)

**Comment by mikkamp** [comment]
Hi @galapogos01

In that same diff there was also a hook which was added for making the script async, see: 
https://github.com/woocommerce/woocommerce-google-analytics-integration/blob/1.8.2/includes/class-wc-google-analytics.php#L720-L726

Although based on your snippet it looks like there is some other plugin/code which is adding `type='text/javascript'` there which is preventing it from matching.

Can you confirm what's hooking into `script_loader_tag` on your site, as we might need to make some adjustments in priority so the two won't conflict.

**Comment by WiredWonder** [comment]
Thanks for the quick reply @mikkamp!

All of my script tags contain `type='text/javascript'`. I am not aware of anything in my configuration that would be doing anything different to stock core/woo. 

I worked around the issue using this:
```
add_filter('script_loader_tag', 'add_async', 10, 2);
 
function add_async($tag, $handle) {
  if($handle !== 'google-tag-manager') {
    return $tag;
  }
   
  return str_replace(' src=', ' async src=', $tag);
}
```

This suggests the hook you mentioned is not firing, as it should be doing essentially the same thing?

**Comment by mikkamp** [comment]
Glad to hear you have a temporary workaround:

> This suggests the hook you mentioned is not firing, as it should be doing essentially the same thing?

I think it should still be firing it's just looking specifically for the text `<script src` so we might need to make that matching pattern a bit more flexible. If I recall adding the src part was to prevent it adding async twice, but seems a bit too restrictive.

**Comment by mikkamp** [comment]
Just wanted to mention that WP 6.3 adds a loading strategy: https://make.wordpress.org/core/2023/07/14/registering-scripts-with-async-and-defer-attributes-in-wordpress-6-3/
We'll still need to remain backwards compatible but probably worth enqueing through the new method if it's available (and skip hooking into `script_loader_tag`).
