### ISSUE TITLE
Add to cart event is fired up when clicking on a product to see details

### ISSUE THREAD

**Issue by mVento3** [woocommerce/woocommerce-google-analytics-integration#330]
### Describe the bug:
When clicking on a product link/image in product list/category, I am getting "add to cart" event fired up

### Steps to reproduce:
1. Click on a product image/link in product list/category
2. Check tag assistant and look for -> view_item_list -> add_to_cart -> Link click

### Expected behavior:
I guess the "add to cart" event shouldn't be fired up when we want to see product details, just "view_item" which is fired up when new page opened up. As I can see, "view_item" event is working correctly.

### Actual behavior:
The event "add_to_cart" is fired up when clicking on a product link/image.

### Additional details:
When actually clicking on "Add to cart" button, the "add_to_cart" event is fired up correctly.
Image below shows how clicking on a product link/image behaves.
![image](https://github.com/woocommerce/woocommerce-google-analytics-integration/assets/7684287/44318c59-cbda-4d6f-aa45-e7de3690a26c)
Plugin version: 1.8.9
WooCommerce version: 7.8.0

**Comment by eason9487** [comment]
Hi @mVento3,

with the same steps and setup:

> ### Steps to reproduce:
> 1. Click on a product image/link in product list/category
> 2. Check tag assistant and look for -> view_item_list -> add_to_cart -> Link click

> Plugin version: 1.8.9
> WooCommerce version: 7.8.0

I tried to reproduce this issue with the classical and block product list pages but no luck.
Could you do some [conflict testing](https://woo.com/document/how-to-test-for-conflicts/) and check if you still see the issue when using a theme like Storefront?

**Comment by mVento3** [comment]
@eason9487 Thank you for a quick response, I will check this out.

**Comment by mVento3** [comment]
I couldn't do the conflict testing which was suggested because I don't have much time to do this.
What I did to solve this issue was in [this line of code](https://github.com/woocommerce/woocommerce-google-analytics-integration/blob/487625e0c5bcf61a9c568c0a24ec95c5d63afdd5/includes/class-wc-google-gtag-js.php#L225C55-L225C55) nest additional class for 'a' tag like `.product.post-" . esc_js( $product->get_id() ) . ' a.some_additional_class`
I realize that this is temporary solution for us.

**Comment by jorgemd24** [comment]
Thanks @mVento3 for reporting the issue, I have been able to reproduce the issue and I created the https://github.com/woocommerce/woocommerce-google-analytics-integration/pull/332 to fix the issue.
