### ISSUE TITLE
The `add_to_cart` event is sent incorrectly when clicking the button under the image of an external, bundle, or out-of-stock product

### ISSUE THREAD

**Issue by eason9487** [woocommerce/woocommerce-google-analytics-integration#351]
### Describe the bug:

With a non-block theme, the `add_to_cart` event is sent incorrectly when clicking the button under the product image. This issue happens in these cases:

- External product
   ![image](https://github.com/woocommerce/woocommerce-google-analytics-integration/assets/17420811/ccb0d118-243f-4947-b4cb-12bedcd99643)
- Product bundle
   ![image](https://github.com/woocommerce/woocommerce-google-analytics-integration/assets/17420811/45cac304-c556-4df3-973f-3addfb3c4c48)
- Any out-of-stock simple or grouped products
   ![image](https://github.com/woocommerce/woocommerce-google-analytics-integration/assets/17420811/31d362b6-f6a4-426a-a957-6e928ff9cd1b)

### Steps to reproduce:

1. Install and activate [Woo Product Bundles](https://woo.com/products/product-bundles/).
2. Set up a non-block theme, e.g. **Storefront**.
3. Set up this extension:
   - Select "Use Global Site Tag" and all Tracking Options.
   - Enable "Enable Enhanced eCommerce" and all sub-options.
4. Set up DevTool:
   - Open browser's DevTool and switch to the Network tab.
   - Tick "Preserve log".
   - Select "All" and filter the keyword by "en=add_to_cart"
   - ![image](https://github.com/woocommerce/woocommerce-google-analytics-integration/assets/17420811/5034b33f-5ffd-4aee-b3ee-79c52d294cdd)
5. Set up products:
   - Set up a simple product and set it as out of stock.
   - Set up a product with the "Product bundle" type.
   - Set up a product with the "External/Affiliate product" type. 
6. Go to the shop list page.
7. Click the button of each product set in step 5.
8. Switch to the Network tab of DevTool to inspect requests.

https://github.com/woocommerce/woocommerce-google-analytics-integration/assets/17420811/63647767-3409-40b2-839e-911e03727044

### Expected behavior:

The `add_to_cart` event should not be sent when the behavior of clicking the button is to navigate to its product page.

### Actual behavior:

The `add_to_cart` event may be sent when clicking a button to navigate to a product page.

**Comment by martynmjones** [comment]
Re-tested with #322 and the `add_to_cart` event is no longer incorrectly sent so closing issue.
