### ISSUE TITLE
Plugin does not load tracker if gtag already exists on the window object

### ISSUE THREAD

**Issue by workeffortwaste** [woocommerce/woocommerce-google-analytics-integration#367]
The plugin does not load the tracker if gtag already exists on the window object.

https://github.com/woocommerce/woocommerce-google-analytics-integration/blob/70790675433c81ac83879cdf67fc36ddd238b5d0/assets/js/src/tracker/index.js#L29

This can happen if you're using another plugin or method to implement a different Google property such as Google Ads for example. This change breaks the plugin across all our clients completely disabling GA if they update to 2.0 😬

**Comment by jorgemd24** [comment]
Thanks @workeffortwaste for reporting this! 

Could you use the following filter `woocommerce_gtag_tracker_variable ` to see if it resolves the issue for you?

https://github.com/woocommerce/woocommerce-google-analytics-integration/blob/70790675433c81ac83879cdf67fc36ddd238b5d0/includes/class-wc-google-gtag-js.php#L182

Example:
```
add_filter('woocommerce_gtag_tracker_variable', function ($arg){
	return 'wc_gtag';
});
```

Also, could you provide a bit more detail about your setup so we can gain a better understanding of your issue and needs? For instance, it would be helpful to see how you're implementing other Google properties.

Thanks in advance!

**Comment by workeffortwaste** [comment]
Hi @jorgemd24 thanks for the response, adding in the filter does resolve the issue although it causes other problems when plugins/scripts are expecting the tracker to be gtag.

Over a wide range of clients many have Google Ads added via plugins or manually to the head, with the standard gtag script.

**Comment by workeffortwaste** [comment]
Hi @jorgemd24 thanks for the response, adding in the filter does resolve the issue although I'm not particularly fond of that being a required solution as it causes other problems when plugins/scripts/extensions are expecting the tracker to be named gtag. There's even several direct references to `window.gtag` in this plugin which would fail.

Over a wide range of clients many have Google Ads added via plugins or manually to the head, with the standard gtag script.

```
<!-- Google tag (gtag.js) - Google Ads: AW-XXXXXX -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=AW-XXXXXX"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config','AW-XXXXXX');
  </script>
```

I know it's possible to load both AW-XXXXXX and G-XXXXX tags with a single tracker script but in most real world scenarios nearly everyone has doubled up on the code, especially when GA and Ads are usually handled by separate plugins.

Previously this wasn't an issue with v1.x of Google Analytics for WooCommerce but it's now causing issues with v2.0.

It's not only adding the trackers that causes the problem, as for example if a cookie consent trigger fires before Google Analytics for WooCommerce v2.0 initialises with the following code:

```
window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('consent', 'update', {
  'ad_storage': 'granted'
});
```

Then when Google Analytics for WooCommerce loads it will see that gtag exists on the window and fail to initialise.

**Comment by workeffortwaste** [comment]
While not directly relevant you can see that it's valid usage to use `window.dataLayer = window.dataLayer || []; function gtag(){dataLayer.push(arguments);}` multiple times.

Look at the example here from Google which calls it twice: https://developers.google.com/tag-platform/security/guides/consent?consentmode=advanced#gtag.js_3

**Comment by jorgemd24** [comment]
Hi @workeffortwaste, thanks for sharing that link. I guess we could replace this:

https://github.com/woocommerce/woocommerce-google-analytics-integration/blob/70790675433c81ac83879cdf67fc36ddd238b5d0/assets/js/src/tracker/index.js#L29-L40

With this:

```
		if ( ! window[ config.tracker_function_name ] ) {
			window.dataLayer = window.dataLayer || [];
			function gtag() {
				window.dataLayer.push( arguments );
			}

			window[ config.tracker_function_name ] = gtag;
		}
```

Can you check if it will work as expected for you?

**Comment by workeffortwaste** [comment]
Hi @jorgemd24, thanks for that but unfortunately your suggestion doesn't work as intended and throws console errors for me after testing.

The solution is to simply remove these lines.
https://github.com/woocommerce/woocommerce-google-analytics-integration/blob/70790675433c81ac83879cdf67fc36ddd238b5d0/assets/js/src/tracker/index.js#L29-L32

I've tested the above and it works in all scenarios as expected.

**Comment by tomalec** [comment]
Thank you @workeffortwaste for the report and for providing the fix :)

Speaking of `window.gtag` being used, I'll start a new issue to fix than later as well.

**Comment by tomalec** [comment]
@workeffortwaste Speaking of 

> There's even several direct references to `window.gtag` in this plugin which would fail.

I found only one such case, which is not used, and we could remove it as in https://github.com/woocommerce/woocommerce-google-analytics-integration/pull/375

Do you find any more cases of `window.gtag`?

**Comment by workeffortwaste** [comment]
I've had a look and can't see any remaining cases of `window.gtag` 👍
