### ISSUE TITLE
Latest Update Issue

### ISSUE THREAD

**Issue by kingyyyyyy** [woocommerce/woocommerce-google-analytics-integration#368]
### Describe the bug:
Hello,

We see the following error in console, with the new update:-

https://i.gyazo.com/8ae21a0b4145bbf6d5fadfc38e30b55e.png

https://i.gyazo.com/466b3ce707143009319b601167f7fa56.png

We have shown our settings below.

https://i.gyazo.com/afa55784663023309f4a303e01da4016.png

Also, we no longer see most visitors on Real Time on GA (started happening around 2 hours ago)? We have orders coming through and have seen only 2 real time visitors in that time, even though earlier on it was over 20 constantly. 

Tested using Tag Assistant Companion extension and it can’t find a tag on our site, too, anymore?

We don't use Google Ads etc, due to the nature of our business, and I believe this is the only plugin we use for GA.

All plugins on the site are updated.

Any idea how to fix this?

### Expected behavior:
Works like before

### Actual behavior:
Issues outlined above since plugin update and cache clearing.

### Additional details:
`
### WordPress Environment ###

WordPress address (URL): https://myeliquidsupplies.com
Site address (URL): https://myeliquidsupplies.com
WC Version: 8.6.1
REST API Version: ✔ 8.6.1
WC Blocks Version: ✔ 11.8.0-dev
Action Scheduler Version: ✔ 3.7.1
Log Directory Writable: ✔
WP Version: 6.4.3
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.58
PHP Version: 7.4.33
PHP Post Max Size: 120 MB
PHP Time Limit: 300
PHP Max Input Vars: 10000
cURL Version: 7.68.0
OpenSSL/1.1.1f

SUHOSIN Installed: –
MySQL Version: 8.0.36-0ubuntu0.20.04.1
Max Upload Size: 120 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.6.1
WC Database Prefix: wp_
Total Database Size: 1278.56MB
Database Data Size: 813.75MB
Database Index Size: 464.81MB
wp_woocommerce_sessions: Data: 2.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 9.52MB + Index: 3.52MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 108.63MB + Index: 55.14MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.20MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.45MB + Index: 0.41MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 15.02MB + Index: 17.13MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 11.02MB + Index: 8.03MB + Engine InnoDB
wp_cli_scripts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 1.52MB + Index: 1.97MB + Engine InnoDB
wp_comments: Data: 81.61MB + Index: 40.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 1.02MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 12.09MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 89.23MB + Index: 7.08MB + Engine InnoDB
wp_postmeta: Data: 256.80MB + Index: 141.28MB + Engine InnoDB
wp_posts: Data: 17.55MB + Index: 8.06MB + Engine InnoDB
wp_rapidload_job: Data: 0.11MB + Index: 0.00MB + Engine InnoDB
wp_rapidload_job_data: Data: 2.38MB + Index: 0.03MB + Engine InnoDB
wp_rapidload_job_optimizations: Data: 1.50MB + Index: 0.02MB + Engine InnoDB
wp_rapidload_uucss_job: Data: 0.22MB + Index: 0.00MB + Engine InnoDB
wp_rapidload_uucss_rule: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_css: Data: 0.13MB + Index: 0.03MB + Engine InnoDB
wp_revslider_css_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_layer_animations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_revslider_layer_animations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_navigations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_revslider_navigations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_sliders: Data: 0.03MB + Index: 0.03MB + Engine InnoDB
wp_revslider_sliders_bkp: Data: 0.03MB + Index: 0.00MB + Engine InnoDB
wp_revslider_slides: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_revslider_slides_bkp: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_revslider_static_slides: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_revslider_static_slides_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_smush_dir_images: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.36MB + Index: 0.20MB + Engine InnoDB
wp_term_taxonomy: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.19MB + Index: 0.13MB + Engine InnoDB
wp_terms: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 10.52MB + Index: 8.03MB + Engine InnoDB
wp_users: Data: 1.52MB + Index: 0.36MB + Engine InnoDB
wp_vivawallet_data: Data: 0.14MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 1.52MB + Index: 1.67MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 7.52MB + Index: 7.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.09MB + Index: 0.13MB + Engine InnoDB
wp_wc_order_operational_data: Data: 5.52MB + Index: 3.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 9.52MB + Index: 7.06MB + Engine InnoDB
wp_wc_order_stats: Data: 3.52MB + Index: 3.48MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 2.52MB + Index: 1.97MB + Engine InnoDB
wp_wc_orders: Data: 11.52MB + Index: 12.97MB + Engine InnoDB
wp_wc_orders_meta: Data: 136.67MB + Index: 127.66MB + Engine InnoDB
wp_wc_points_rewards_user_points: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_points_rewards_user_points_log: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 3.31MB + Index: 3.30MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 3.52MB + Index: 3.36MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wcpdf_invoice_number: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_wcpdf_packing_slip_number: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wdr_order_discounts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wdr_order_item_discounts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wdr_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wmfo_fraud_attempts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wmfo_logs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woodmart_wishlist_products: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woodmart_wishlists: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpae_blocked_ip: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpae_spam_data: Data: 0.14MB + Index: 0.00MB + Engine InnoDB
wp_wpae_spammer_ip: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpae_submission_id: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpfm_backup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_debug_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpr_rocket_cache: Data: 0.09MB + Index: 0.14MB + Engine InnoDB
wp_wpr_rucss_used_css: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_yoast_indexable: Data: 1.52MB + Index: 0.22MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.08MB + Index: 0.16MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.06MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

attachment: 823
cms_block: 16
custom_css: 1
mc4wp-form: 1
nav_menu_item: 81
oembed_cache: 13
page: 18
post: 17
product: 560
product_variation: 21939
shop_coupon: 25
shop_order: 26439
shop_order_refund: 86
vg_gateway_condition: 3
wp_navigation: 1
wp_template: 2
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (39) ###

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.1
Autoptimize: by Frank Goossens (futtta) – 3.1.10
Cloudflare: by Cloudflare Inc. – 4.12.6

Code Snippets: by Code Snippets Pro – 3.6.2
Conditional Payment Methods For WooCommerce: by StoreApps – 4.1.0
Contact Form 7: by Takayuki Miyoshi – 5.9
Free Shipping Label: by Devnet – 3.0.1
WP Armour - Honeypot Anti Spam: by Dnesscarkey – 2.1.15
WPBakery Page Builder: by Michael M - WPBakery.com – 7.5
Mailchimp for WooCommerce: by Mailchimp – 3.6
MC4WP: Mailchimp for WordPress: by ibericode – 4.9.11
Slider Revolution: by ThemePunch – 6.6.20
AG Opayo (Formerly SagePay) Server - WooCommerce Gateway: by Aaron Bowie – 1.6.4
Simple Cloudflare Turnstile: by Elliot Sowersby RelyWP – 1.25.0

Trustpilot-reviews: by Trustpilot – 2.5.925
Unbranded E Liquid Formula Calculator: by ZHORA Studio – 1.0
RapidLoad 2.2 - Speed Monster in One Plugin: by RapidLoad – 2.2.15
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 2.24.1.26

User Role Editor: by Vladimir Garagulya – 4.64.2
Viva Wallet Smart Checkout: by Viva Wallet – 3.6.8
WooCommerce Dynamic Pricing & Discounts: by RightPress – 2.4.6
Premmerce Permalink Manager for WooCommerce: by Premmerce – 2.3.11
Country Based Restrictions for WooCommerce: by zorem – 3.6.1
Google Analytics for WooCommerce: by WooCommerce – 2.0.0
PDF Invoices & Packing Slips for WooCommerce: by WP Overnight – 3.7.7
PDF Invoices & Packing Slips for WooCommerce - Premium Templates: by WP Overnight – 2.21.5
Product SKU Generator for WooCommerce: by SkyVerge – 2.5.0
WooCommerce Store Credit: by KoiLab – 4.5.1
WooCommerce Table Rate Shipping: by WooCommerce – 3.1.6
WooCommerce Xero Integration: by WooCommerce – 1.8.4
WooCommerce: by Automattic – 8.6.1
Woodmart Core: by  – 1.0.42
Yoast SEO: by Team Yoast – 22.2
WP Armour Extended - Honeypot Anti Spam: by Dnesscarkey – 1.26
WP Mail SMTP: by WP Mail SMTP – 4.0.1
WP Rocket - D-bugger: by WP Rocket Support Team –
WP Rocket: by WP Media – 3.15.9
Smush: by WPMU DEV – 3.15.5
WPS Hide Login: by WPServeur NicolasKulka wpformation – 1.9.13.2

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
store_credit (store_credit)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to Woo.com: –
Enforce Approved Product Download Directories: –
HPOS feature screen enabled: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: ✔

### WC Pages ###

Shop base: #15 - /shop/
Basket: #16 - /basket/
Checkout: #17 - /checkout/
My account: #18 - /my-account/
Terms and conditions: #33 - /terms-conditions/

### Theme ###

Name: Woodmart Child
Version: 1.0.0
Author URL: http://xtemos.com
Child Theme: ✔
Parent Theme Name: Woodmart
Parent Theme Version: 7.4.3
Parent Theme Author URL: http://themeforest.net/user/xtemos
WooCommerce Support: ✔

### Templates ###

Overrides: woodmart/woocommerce/archive-product.php
woodmart/woocommerce/cart/cart-item-data.php
woodmart/woocommerce/cart/cart.php
woodmart/woocommerce/cart/cross-sells.php
woodmart/woocommerce/cart/mini-cart.php
woodmart/woocommerce/checkout/form-checkout.php
woodmart/woocommerce/checkout/thankyou.php
woodmart/woocommerce/content-product-cat.php
woodmart/woocommerce/content-product.php
woodmart/woocommerce/content-single-product.php
woodmart/woocommerce/content-widget-product.php
woodmart-child/woocommerce/emails/customer-completed-order.php
woodmart-child/woocommerce/emails/customer-processing-order.php
woodmart-child/woocommerce/emails/email-styles.php
woodmart/woocommerce/global/breadcrumb.php
woodmart/woocommerce/global/form-login.php
woodmart/woocommerce/global/quantity-input.php
woodmart/woocommerce/loop/add-to-cart.php
woodmart/woocommerce/loop/loop-end.php
woodmart/woocommerce/loop/loop-start.php
woodmart/woocommerce/loop/no-products-found.php
woodmart/woocommerce/loop/orderby.php
woodmart/woocommerce/loop/pagination.php
woodmart/woocommerce/loop/sale-flash.php
woodmart/woocommerce/myaccount/form-login.php
woodmart/woocommerce/product-searchform.php
woodmart/woocommerce/single-product/add-to-cart/grouped.php
woodmart/woocommerce/single-product/add-to-cart/variable.php
woodmart/woocommerce/single-product/meta.php
woodmart/woocommerce/single-product/product-attributes.php
woodmart/woocommerce/single-product/product-image.php
woodmart/woocommerce/single-product/product-thumbnails.php
woodmart/woocommerce/single-product/rating.php
woodmart/woocommerce/single-product/related.php
woodmart/woocommerce/single-product/sale-flash.php
woodmart/woocommerce/single-product/tabs/description.php
woodmart/woocommerce/single-product/tabs/tabs.php
woodmart/woocommerce/single-product/title.php
woodmart/woocommerce/single-product/up-sells.php
woodmart/woocommerce/single-product-reviews.php
woodmart/woocommerce/single-product.php

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
product-linked
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-pre-publish-modal
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2024-03-07 00:19:12 +00:00
Options: ✔
Notes: 9
Onboarding: completed

### Action Scheduler ###

Complete: 40,422
Oldest: 2024-02-04 14:41:03 +0000
Newest: 2024-03-06 14:34:19 +0000

Pending: 4
Oldest: 2024-03-06 15:34:19 +0000
Newest: 2024-03-07 02:49:34 +0000

### Store Credit ###

Prices entered with tax: yes
Show My Account: yes
Delete after use: yes
Individual use: yes
Include tax: no
Apply to shipping: yes
Coupon code format: {coupon_code}
Overrides: -

### Status report information ###

Generated at: 2024-03-06 14:37:03 +00:00
`

**Comment by jorgemd24** [comment]
Hi @kingyyyyyy, thanks for reporting this issue!

I haven't been able to reproduce the issue locally however I visited your website: https://myeliquidsupplies.com/ and I saw the same error that you mentioned:

![image](https://github.com/woocommerce/woocommerce-google-analytics-integration/assets/2488994/76074b03-256d-42c7-9e2f-4c4c4cc24283)

It seems that you use Cloudflare (rocket-loader) so it could be related to a cache issue. 

In the dev console, If I type `window.wcgai.trackClassicPages` I see that trackClassicPages is defined, so another guess could be that something is calling the script before the trackClassicPages is set. 

![image](https://github.com/woocommerce/woocommerce-google-analytics-integration/assets/2488994/e0fbca9f-2647-4a04-a831-dd4a5a04309d)

Could you share with me the trace of what's invoking trackClassicPages? Something similar to what you shared here: https://i.gyazo.com/8ae21a0b4145bbf6d5fadfc38e30b55e.png, but perhaps the dev console shows a bit more details about what's calling that function.

**Comment by kingyyyyyy** [comment]
Hello,

Rocket Loader via CF has now been turned off, so you can see the error as provided now. 

I can only see the error when not logged in. Please try in Incognito.

The error is showing on every page: https://i.gyazo.com/c43fdaedad7af04a48981ee0794ae3e3.png

**Comment by kingyyyyyy** [comment]
In Source view I see these two calling that function, when on a product page:-

**Comment by mikkamp** [comment]
Hi @kingyyyyyy 

I had another look at your site and it seems you are using the [Autoptimize plugin](https://wordpress.org/plugins/autoptimize/).

This can change the load order of the scripts both for inline scripts and static scripts. It seems you have the option to defer inline scripts disabled, but the static script for the plugin is deferred. If you are going to leave that option disabled then I'd suggest to also prevent the main JS file from being deferred. Can you setup an exclusion for `woocommerce-google-analytics-integration`.

![image](https://github.com/woocommerce/woocommerce-google-analytics-integration/assets/11388669/eb190104-bb80-4cfa-be32-287a82f6f3e5)

Then save the options and clear the cache. If that doesn't resolve the issue, can you clarify what settings you are using?

**Comment by kingyyyyyy** [comment]
We have added as suggested: https://i.gyazo.com/11771226f37bba27f2a5e2f2b898fb1e.png

Cleared Autoptimize, WP Rocket and Cloudflare, and now that error seems to have disappeared, which is great! 

Thank you so much!

--

Regarding this: "Tested using Tag Assistant Companion extension and it can’t find a tag on our site, too, anymore?" - it seems because we're logged in the gtag isn't added, but trying on another browser when not logged in works, so this is all fine.

 --

Just this issue now: "we no longer see most visitors on Real Time on GA. We have orders coming through and have seen only 2 real time visitors in that time, even though earlier on it was over 20 constantly."

I see, even now as this is written, much fewer visitors, and when I connect via Chrome Incognito on desktop, or normal Chrome on mobile, it doesn't show me in Real Time anymore? It started happening today. it just shows a fraction of visitors as can be seen: https://i.gyazo.com/65580cf095057d6361d1ecd157e9eaf6.png

Edit: However, when I connect on Desktop Firefox it shows me?

**Comment by tomalec** [comment]
The drop in tracked visitors may be related to the fact that, starting March 6th, Google requires user consent to track data.
2.0.0, to follow Google's Consent Mode and [EEA](https://en.wikipedia.org/wiki/European_Economic_Area) regulation rules, disalow this consent by default.

Are you or your visitors connecting to your site coming from Europe?

**Comment by kingyyyyyy** [comment]
Hello,

Yes, this seems to be the case.

Any suggestions on plugins to use that integrate with yours, to enable Consent 2?

Does Complianz work with your plugin? As Complianz seems to be the only excellent rated plugin that has a one-off purchase cost instead of a monthly subscription, and includes unlimited subpages.

**Comment by tomalec** [comment]
I haven't run a full integration test yet, but from what I can see in the Complianz codebase, they're using the `gtag('consent', 'update',...)` API, so it should work well together.

Also, if your [CMP](https://support.google.com/tagmanager/answer/14009343#web-consent) sets/updates the consent asynchronously, you may consider using [`wait_for_update`](https://developers.google.com/tag-platform/security/guides/consent?hl=en&consentmode=advanced#default-consent) flag in [Remove unused function from formatters](https://github.com/woocommerce/woocommerce-google-analytics-integration/pull/375#top), something like:
```php
add_filter( 'woocommerce_ga_gtag_consent_modes', function ( $consent_modes ) {
    $consent_modes[0]['wait_for_update'] = 500;
    return $consent_modes;
} );
```

**Comment by puntope** [comment]
All the mentioned issues have been addressed. So I'm closing this issue

- Fatal error -- Merchant problem with cache
- No records being tracked in gtag -- Merchant was logged in
- No real-time -- No content given for Europe - solved by adding provided snippets.  

Please feel free to reopen a new issue if more problems come in.

**Comment by puntope** [comment]
btw. @kingyyyyyy I edited https://github.com/woocommerce/woocommerce-google-analytics-integration/issues/368#issuecomment-1981359656 as it was showing your GA ID in the screenshot
