### ISSUE TITLE
Critical errors with v.2.0.0

### ISSUE THREAD

**Issue by SirRahikkala** [woocommerce/woocommerce-google-analytics-integration#371]
When adding zero value products to cart the plugin gives Uncaught TypeError: array_keys(): Argument #1 ($array) must be of type array, string given in /wp-content/plugins/woocommerce-google-analytics-integration/includes/class-wc-abstract-google-analytics-js.php:244 

nginx/1.24.0, PHP 8.0.30, Woocommerce 8.6.1,

**Comment by tomalec** [comment]
Hi @SirRahikkala, We were not able to reproduce the issue with zero-value products.

But we managed to get the same error by mimicking (via code) a product with no attributes.
https://github.com/woocommerce/woocommerce-google-analytics-integration/pull/372
Please let me know if that solves the problem for you.

If not, could you please give more detailed steps to reproduce your case?

**Comment by SirRahikkala** [comment]
The products which see this error do have attributes which are weights so this is not about those. Could these screenshots point more forward?

![Näyttökuva 2024-03-07 193040](https://github.com/woocommerce/woocommerce-google-analytics-integration/assets/7370720/0c30e4ae-0c62-4044-9ffc-e1e9e62bd4ff)


![Näyttökuva 2024-03-07 192923](https://github.com/woocommerce/woocommerce-google-analytics-integration/assets/7370720/e775acac-5a39-4b4c-b3ac-5c35803f1b6e)

**Comment by SirRahikkala** [comment]
Update 2.0.1 fixed the issue.
