### ISSUE TITLE
v2.0.0 - Some events doesn't trigger anymore

### ISSUE THREAD

**Issue by puntope** [woocommerce/woocommerce-google-analytics-integration#377]
### Describe the bug:

After the update, even with all the consent granted, some of the track events are not being triggered properly.

### Affected events
 
- [ ] Shop Page - Add to cart
- [ ] shop page - view item List

### Expected behavior:

Same as in v1.8.0

https://github.com/woocommerce/woocommerce-google-analytics-integration/assets/5908855/79f5fbd0-7399-4a7e-a663-377e64accec2

https://github.com/woocommerce/woocommerce-google-analytics-integration/assets/5908855/d595b40f-7eb0-40ff-a7f4-5262590626d3

### Actual behavior:

https://github.com/woocommerce/woocommerce-google-analytics-integration/assets/5908855/df0e154a-8fd4-4a3a-a239-d3ffe4cfa770

### Additional Details

Tested in different fresh sites with the next configs and in all of them it fails:

- WC 8.7-rc1 / WP 6.5-rc1
- WC 8.6.1 / WP 6.5-rc1
- WC 8.6.1 / WP 6.4

**Comment by puntope** [comment]
I think its caused because the way we fetch the products and handle  the events in the classic page works. 

https://github.com/woocommerce/woocommerce-google-analytics-integration/blob/trunk/assets/js/src/integrations/classic.js#L114

But the hook events for the Product Boock are not being triggered

**Comment by PaulSchiretz** [comment]
I want to add here that also on classic single product pages the add to cart event triggers a js error rather than triggering the event.

The cause is that the classic single product pages have the product id as value of the add_to_cart button rather than a separate data-product_id attribute. But parsing in classic.js is always done on the product_id attribute as can be seen here:

```
	// Handle runtime cart events.
	/**
	 * Track the custom add to cart event dispatched by WooCommerce Core
	 *
	 * @param {Event}         e         - The event object
	 * @param {Object}        fragments - An object containing fragments of the updated cart.
	 * @param {string}        cartHash  - A string representing the hash of the cart after the update.
	 * @param {HTMLElement[]} button    - An array of HTML elements representing the add to cart button.
	 */
	document.body.onadded_to_cart = ( e, fragments, cartHash, button ) => {
		tracker.eventHandler( 'add_to_cart' )( {
			product: getProductFromID(
				parseInt( button[ 0 ].dataset.product_id ),
				products,
				cart
			),
		} );
	};
```
