### ISSUE TITLE
SyntaxError Unexpected token '&' why?

### ISSUE THREAD

**Issue by khalilgharbaoui** [woocommerce/woocommerce-google-analytics-integration#383]
Since the upgrade i have been getting errors in my Sentry and this is where it happens
Seems that this: `gtag(&quot;event&quot;, &quot;page_view&quot;, {send_to: &quot;GLA&quot;}); `
Is escaped when it should not be 🤔 
```
<script type="text/javascript" id="woocommerce-google-analytics-integration-js-after">

/* <![CDATA[ */

gtag("config", "REDACTED", { "groups": "GLA", "send_page_view": false });

gtag(&quot;event&quot;, &quot;page_view&quot;, {send_to: &quot;GLA&quot;});    <<<<

/* ]]> */

</script>
```

any thoughts? 💭

**Comment by ianlin** [comment]
Hi @khalilgharbaoui, thanks for reporting this issue. Can you please provide more information like which version you are using and also the steps to reproduce the issue?

**Comment by puntope** [comment]
@khalilgharbaoui Also if possible to paste the Sentry error here it might be really helpful.

**Comment by martynmjones** [comment]
Hey @khalilgharbaoui, 

Thanks again for reporting this issue. We were able to replicate and it has been addressed in https://github.com/woocommerce/google-listings-and-ads/pull/2312 which will be included in the next version of Google Listings & Ads released next week. I'm closing this issue but please do let us know if you have any further issues after the extension updates.

**Comment by khalilgharbaoui** [comment]
> Hey @khalilgharbaoui, 
> 
> Thanks again for reporting this issue. We were able to replicate and it has been addressed in https://github.com/woocommerce/google-listings-and-ads/pull/2312 which will be included in the next version of Google Listings & Ads released next week. I'm closing this issue but please do let us know if you have any further issues after the extension updates.

@martynmjones glad i could help.
