### ISSUE TITLE
Upgrading to 2.0.0 - Purchase Events Not Including Transaction ID

### ISSUE THREAD

**Issue by tabertantrum** [woocommerce/woocommerce-google-analytics-integration#387]
### Describe the bug:
Since upgrading to 2.0.0 last week we no longer see specific Transaction IDs being sent to GA4, and conversion data is significantly overstated. All purchase events are being sent with a value and items, but the Order ID is not being sent.

### Steps to reproduce:
1. Complete a purchase on a site using GA4 transaction tracking.
2. Observe the collect event sent to GA4.

### Expected behavior:
The purchase event sent to GA4 should include a unique transaction identifier, previously Order ID was sent under the UA configuration.

### Actual behavior:
Transaction ID is no longer sent, only currency, items, and value.

### Additional details:
~~Conversion amounts seem to be drastically overstated since the change as well, although this could be due to the nature of not having a unique transaction identifier within GA4 so each purchase is additive.~~
I found the note on a forum post to revert to 1.8.14 due to incorrect values being posted. However, I believe this missing Transaction ID reference should be included in the fix for that (#380).

**Comment by mikkamp** [comment]
Hi @tabertantrum 

Thanks for reporting the issue. I can confirm that the transaction ID isn't being sent with the purchase event. I've submitted a fix for that in #388 

As for the total value being incorrect, we have resolved that in #380 but it hasn't been released yet.

We are hoping to be able to bundle those changes in a new release soon. Thanks for your patience, hopefully reverting to 1.8.14 hasn't caused you too many issues.
