### ISSUE TITLE
Issue in woocomerce / xstore theme

### ISSUE THREAD

**Issue by augpaschal** [woocommerce/woocommerce-google-analytics-integration#390]
We have installed version 2.0.1  in woocommerce. For 3-4 days it has stopped writing in analytics

**Comment by ianlin** [comment]
Hi @augpaschal, thanks for reporting the issue. We are working on [several issues](https://github.com/woocommerce/woocommerce-google-analytics-integration/issues?q=is%3Aissue+label%3Av2.0.0+) regarding the version >= 2.0.0. We will release a new version soon, however it'd still be great if you'd like to provide more information regarding the issue you encountered, such as the screenshot of the error, or the step to reproduce, etc.

**Comment by puntope** [comment]
Closed in favor of https://github.com/woocommerce/woocommerce-google-analytics-integration/issues/377
