### ISSUE TITLE
Add filter to disable consent mode defaults

### ISSUE THREAD

**Issue by martynmjones** [woocommerce/woocommerce-google-analytics-integration#405]
### Describe the bug:
Some third-party plugins that include functionality to grant consent will also set defaults on page load. To support as many configurations as possible we should add a filter to disable consent defaults in Google Analytics for WooCommerce.

Reported: https://wordpress.org/support/topic/consent-mode-issue/

**Comment by tomalec** [comment]
We have the `woocommerce_ga_gtag_consent_modes` filter. You can use it to disable it completely, by returning an empty array
```php
add_filter( 'woocommerce_ga_gtag_consent_modes', function ( $consent_modes ) {
   return array();
} );
```
