### ISSUE TITLE
QIT workflow failed at the last step which it tried to parse results and populate GHA outputs

### ISSUE THREAD

**Issue by ianlin** [woocommerce/woocommerce-google-analytics-integration#415]
### Describe the bug:

Same as the issue woocommerce/google-listings-and-ads#2355

While I was doing [WC 8.8 compatibility test](https://automatap2.wordpress.com/2024/03/20/pt-woocommerce-8-8-compatibility-for-automata-extensions/) and found the QIT workflow failed at the last step which [it tried to parse results and populate GHA outputs](https://github.com/woocommerce/grow/blob/472647d2b8d77b3e59ef9c0d5d9da552dc10b0cd/packages/github-actions/actions/run-qit-annotate/action.yml#L79).

The QIT test itself was successful, as we can see it in [QIT results dashboard](https://qit.woo.com/?qit_results=4582253.MD7WHpsunkFUgeUCyg5CfvrctHrXA6D7eilPAMKKg4RjGgwiZ5rO6RUAeN1BqFuW)

### Steps to reproduce:

1. Run a new [QIT workflow](https://github.com/woocommerce/woocommerce-google-analytics-integration/actions/workflows/run-qit.yml), or just refer to [this one](https://github.com/woocommerce/woocommerce-google-analytics-integration/actions/runs/8595606636) that was already ran.
2. You should see `Run QIT Tests activation (4582252): success - No errors detected.`
3. You should also see `Run QIT Tests The template is not valid. woocommerce/grow/actions-v1/run-qit-annotate/action.yml (Line: 79, Col: 12): Error reading JToken from JsonReader. Path '', line 0, position 0.`

### Expected behavior:

The last step of QIT workflow should passed without any error.

### Actual behavior:

The last step of QIT workflow was failed when parsing results and populates GHA outputs.

**Comment by tomalec** [comment]
The thing is, the QIT `security` test does not take `woocommerce_version` option:
```
The "--woocommerce_version" option does not exist.  
```

See https://github.com/woocommerce/qit-cli/issues/136.

So, I think it's more of a matter of specifying the option caveat in the compact testing checklist.

**Comment by ianlin** [comment]
> The thing is, the QIT security test does not take woocommerce_version option:
> > The "--woocommerce_version" option does not exist. 

Ah you're right, thanks for clarifying. I'm closing this issue as this is more of an options selection guide. The options of running QIT for WC compatibility should be like:

<img width="316" alt="Screenshot 2024-04-10 at 12 12 11" src="https://github.com/woocommerce/google-listings-and-ads/assets/914406/d415075e-9de5-4d3f-8bb4-acf09013e9ef">
