### ISSUE TITLE
Consider using SKU as `item_id` instead of the WordPress post ID

### ISSUE THREAD

**Issue by martincpt** [woocommerce/woocommerce-google-analytics-integration#471]
## User Story
Currently, your plugin uses the WordPress post ID as the `item_id` sent to Google Analytics for events such as "add to cart" or "purchase."

This is problematic because the product ID isn't always permanent, and the Google Analytics tracking may become inaccurate if products are re-uploaded, or if the site is reinstalled. This results in inconsistent tracking.

## Desired Solution
Since product/post IDs can change—especially when products are re-uploaded into new entries or when the site is reinstalled—using the SKU would be a more reliable choice.

SKUs can be reused across sites, whereas product IDs are not necessarily consistent.

Even the Google Analytics documentation recommends using SKU values in their examples:
[Google Analytics Events Documentation](https://developers.google.com/analytics/devguides/collection/ga4/reference/events?sjid=6270165804914473196-EU&client_type=gtag#add_to_cart_item)

## Technical
The SKU should be attached to the product data, which is available under the window.ga4w variable.

**Comment by mikkamp** [comment]
Hi @martincpt 

It is correct that the Product ID is used by default. However there is a setting to choose what kind of identifier is used. Can you go to WooCommerce > Settings > Integrations > Google Analytics and confirm the Product Identification is set to SKU.

![Image](https://github.com/user-attachments/assets/44d11ad9-bd29-4924-8a0a-60b76f087c7b)

**Comment by martincpt** [comment]
Hi @mikkamp 

I can confirm that the Product Identification is set to SKU under WooCommerce > Settings > Integrations > Google Analytics. However, it still appears to use the post ID regardless of this setting. Could this be caused by using WCML (WooCommerce Multilingual)?

**Comment by mikkamp** [comment]
Thanks for clarifying. If that setting is enabled it just uses the default WooCommerce function to [retrieve the SKU](https://woocommerce.github.io/code-reference/classes/WC-Product.html#method_get_sku) and falls back to the ID prefixed with a `#` if the SKU is not available. So there isn't a whole lot the extension itself does there.

It's possible that WooCommerce Multilingual could interfere with which SKU is returned, you might want to check with their developers if there is a specific way to configure the SKU, or how it should be setup for multiple languages.
