### ISSUE TITLE
 503 Service Unavailable

### ISSUE THREAD

**Issue by alinpascaru** [woocommerce/woocommerce-google-analytics-integration#75]
Hello,

I have installed the last versions of "Woocommerce" and "WooCommerce Google Analytics Integration".
In the "Integration" tab, when i press "Save", I'm getting the next error:

"503
Service Unavailable
The server is temporarily busy, try again later"

How can I fix it and save settings?

Have a good day!

**Comment by reason8910** [comment]
Im having the same issue, everytime I try and same back-emd settings.
Wordpress 4.6.1 and WC 2.6.4

Note: Proudly powered by LiteSpeed Web Server

**Comment by laurendavissmith** [comment]
Closing, please reopen if you still have issues with the latest WooCommerce
