### ISSUE TITLE
Preferred Setup in Enhanced ECommerce

### ISSUE THREAD

**Issue by dillonbailey** [woocommerce/woocommerce-google-analytics-integration#77]
Hello!

In GA's enhanced ecommerce settings users are encourages to set checkout "steps" - depending on how the plugin is setup to trigger the steps we can provide useful labels.

For instance:

<img width="1160" alt="screen shot 2016-02-18 at 1 05 04 pm" src="https://cloud.githubusercontent.com/assets/1067872/13131545/44e5d912-d640-11e5-873f-bd116905dd2b.png">

We should provide the "funnel steps"...

**Comment by galbaras** [comment]
+1

**Comment by starflower** [comment]
Is this possible yet? Or what's the solution for this problem?

**Comment by budzanowski** [comment]
What this Enhancement is about https://support.google.com/analytics/answer/6014872?hl=en#cba

**Comment by laurendavissmith** [comment]
This functionality is already built into the Pro version of Google Analytics so to not duplicate those efforts we'll be leaving it out of the free version

You can view a comparison here: https://docs.woocommerce.com/document/woocommerce-google-analytics-pro-vs-free/
