### ISSUE TITLE
Suhosin default values cause plugin settings data loss

### ISSUE THREAD

**Issue by vguerrerobosch** [woocommerce/woocommerce-google-analytics-integration#87]
When submitting plugin settings under Integrations, suhosin `post.max_array_index_length` default value 64 causes data loss on `$_POST` variable, because some array keys are too long (ex: `woocommerce_google_analytics_ga_enhanced_ecommerce_tracking_enabled` ).

Maybe shorter names would improve plugin compatibility with common server configurations.

**Comment by roykho** [comment]
After thinking more on this, if we change the setting name, it would affect existing sites that have this option either enabled or disabled. Not unless we do complicated checks like first check the old settings name if found, then use that and update the meta to the new "shorten" name...etc.

cc @laurendavissmith - do you want to go down that route?

**Comment by laurendavissmith** [comment]
Hmm, what about using a filter to at least let it be easily overridden?

**Comment by roykho** [comment]
Filter would not work here because it will still initially break people's site. So this is either fix or won't fix type issue. Fix would just mean we need to use hacky ways to get around this.

**Comment by vguerrerobosch** [comment]
I would suggest checking for `extension_loaded('suhosin) && ini_get('suhosin.post.max_array_index_lenght < $length` and do filter in that case. You would not break current working sites and fix new ones or not properly configured.

**Comment by roykho** [comment]
There is no easy way to fix this other than perhaps an upgrade routine. Adding a filter will break sites that are currently on suhosin with limit removed. So for now we'll just document this to have users up the limit if they encounter such save errors.

We'll look more into this in a future major release so not to upset anyone's site.
