### ISSUE TITLE
Call to undefined method WC_Product_Simple::get_id()

### ISSUE THREAD

**Issue by virajsoni06** [woocommerce/woocommerce-google-analytics-integration#96]
Hi,
Since the last update(1.4.2) whenever I add anything to my cart, the page throws a Fatal error. It is caused only when this plugin is enabled.

Here's an image for the same. 
![image](https://cloud.githubusercontent.com/assets/13236286/26043830/05d4a802-395e-11e7-8a2d-9f9c0df5f6d0.png)

Can we get this sorted out asap.

**Comment by mattyza** [comment]
@virajsoni06 - Thanks for reporting this.

Based on the error message, I would assume you're using WooCommerce 2.6.x and not WooCommerce 3.0.x? Is that correct?

**Comment by bor0** [comment]
That's weird.

In 3.0:
`class WC_Product_Simple extends (WC_Product extends (WC_Abstract_Legacy_Product extends WC_Data))`, and `WC_Data` has a definition of `get_id`.

In 2.6:
`class WC_Product_Simple extends WC_Product`, and `WC_Product` has a definition of `get_id`.

**Comment by virajsoni06** [comment]
@mattyza The error is coming from a site where the Woocommerce version is 2.3.9

I have another installation with the same plugin version but the Woocommerce version is 2.6.14 and it works fine on it.

The site with Woocommerce version 2.3.9 wasn't causing any problems until before the last 2 updates. It was tracking data properly. 

Can we add a conditional check to see if Woocommerce version is `< 3.0` and call the id() function accordingly?

**Comment by bor0** [comment]
@virajsoni06 here is a patch that you can use to fix that instance: [productid.diff.zip](https://github.com/woocommerce/woocommerce-google-analytics-integration/files/1013704/productid.diff.zip)

Note that we're dropping support for WC versions lower than 2.6 throughout all of the extensions.
