### ISSUE TITLE
Data mismatch with Woocommerce reports

### ISSUE THREAD

**Issue by virajsoni06** [woocommerce/woocommerce-google-analytics-integration#97]
Hi,

I've been running this plugin on one of my client's website for few weeks now and when I compare the number of transactions and revenue for the same duration in Google Analytics and Woocommerce reports, the data does not math. 
The revenue recorded by Google Analytics is  less, most of time. What could be the possible cause for this?

Possible reasons I think it could be because of either of the following reasons - 
- Adblocker installed on user's browsers?
- Placing orders from admin dashboard are not tracked?

Please note that I have the latest version of the plugin installed and the Woocommerce version installed is 2.6. And the only way analytics code is added into the website is through this plugin.

Thanks

**Comment by mattyza** [comment]
Hi @virajsoni06.

I'd say the second is most likely- orders being added through WP Admin.

Orders added through WP Admin aren't tracked by Google Analytics, as these don't involve the frontend at all and thus don't involve the conversion funnels, etc, which Google Analytics encourages.

**Comment by BusinessBloomer** [comment]
Yes, if you're logged in as admin, the GA script is not output on the front-end

**Comment by laurendavissmith** [comment]
Closing, we can reopen if the issue remains
