### ISSUE TITLE
Invalid gist URL in readme (opt-out snippet)

### ISSUE THREAD

**Issue by diggy** [woocommerce/woocommerce-google-analytics-integration#99]
* https://wordpress.org/plugins/woocommerce-google-analytics-integration/#faq
* https://github.com/woocommerce/woocommerce-google-analytics-integration/blob/master/readme.txt#L57

**Comment by lukecav** [comment]
Looks like the reference Gist link account was deleted.

**Comment by lvl99** [comment]
+1

**Comment by laurendavissmith** [comment]
Closing since this will be fixed when we tackle #110
